import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from "node:module";
import fs from "node:fs";

const require = createRequire(import.meta.url);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const EXPORT_STUB = '0&&(module.exports={});';

function trimBundledMainJs(bundlePath) {
	let source = fs.readFileSync(bundlePath, 'utf8');
	const exportIdx = source.lastIndexOf(EXPORT_STUB);
	if (exportIdx !== -1) {
		source = source.slice(0, exportIdx + EXPORT_STUB.length);
	}
	if (!source.endsWith('\n')) {
		source += '\n';
	}
	fs.writeFileSync(bundlePath, source, 'utf8');
}

const punycodePath = require.resolve("punycode/");

const punycodeAliasPlugin = {
	name: "punycode-alias",
	setup(build) {
		build.onResolve({ filter: /^punycode\/$/ }, () => ({
			path: punycodePath,
		}));
		build.onResolve({ filter: /^punycode$/ }, () => ({
			path: punycodePath,
		}));
	},
};

const tikzjaxBootstrapPatch = {
	name: 'tikzjax-bootstrap-texdir',
	setup(build) {
		build.onLoad({ filter: /node-tikzjax[\\/]dist[\\/]bootstrap\.js$/ }, async (args) => {
			let contents = await fs.promises.readFile(args.path, 'utf8');
			contents = contents.replace(
				"(0, path_1.join)(__dirname, '../tex')",
				"((typeof window !== 'undefined' && window.__LUATIKZ_TEX_DIR) || (0, path_1.join)(__dirname, '../tex'))",
			);
			return { contents, loader: 'js' };
		});
	},
};

const externalBuiltins = builtinModules.filter(name => name !== 'punycode');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	outfile: 'main.js',
	bundle: true,
	plugins: [punycodeAliasPlugin, tikzjaxBootstrapPatch],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		...externalBuiltins],
	format: 'cjs',
	watch: !prod,
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	platform: 'node',
}).then(() => {
	if (prod) {
		trimBundledMainJs('main.js');
	}
}).catch(() => process.exit(1));
