/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
__export(exports, {
  default: () => LuaTikzPlugin
});
var import_obsidian3 = __toModule(require("obsidian"));

// diagramView.ts
var import_obsidian = __toModule(require("obsidian"));
function downloadSvg(svgText, filename = "tikz-diagram.svg") {
  const blob = new Blob([svgText], { type: "image/svg+xml;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}
function appendTikzError(parent, message, details, onRetry, extraCls) {
  const cls = extraCls ? `tikzjax-hebrew-local-error ${extraCls}` : "tikzjax-hebrew-local-error";
  const errorEl = parent.createDiv({ cls });
  errorEl.createDiv({
    cls: "tikzjax-hebrew-local-error-title",
    text: message
  });
  if (!details && !onRetry) {
    return;
  }
  const buttonRow = errorEl.createDiv({
    cls: "tikzjax-hebrew-local-error-button-row"
  });
  if (onRetry) {
    const retryButton = buttonRow.createEl("button", {
      text: "Retry",
      cls: "tikzjax-hebrew-local-error-button"
    });
    retryButton.addEventListener("click", onRetry);
  }
  if (!details) {
    return;
  }
  const copyButton = buttonRow.createEl("button", {
    text: "Copy error",
    cls: "tikzjax-hebrew-local-error-button"
  });
  copyButton.addEventListener("click", () => __async(this, null, function* () {
    try {
      yield navigator.clipboard.writeText(details);
      new import_obsidian.Notice("Error copied.");
    } catch (e) {
      new import_obsidian.Notice("Could not copy error.");
    }
  }));
  const toggleButton = buttonRow.createEl("button", {
    text: "Show log",
    cls: "tikzjax-hebrew-local-error-button"
  });
  const detailsEl = errorEl.createEl("pre", {
    cls: "tikzjax-hebrew-local-error-details"
  });
  detailsEl.setText(details);
  detailsEl.style.display = "none";
  toggleButton.addEventListener("click", () => {
    const hidden = detailsEl.style.display === "none";
    detailsEl.style.display = hidden ? "block" : "none";
    toggleButton.setText(hidden ? "Hide log" : "Show log");
  });
}
function showTikzError(el, message, details, onRetry) {
  el.empty();
  appendTikzError(el, message, details, onRetry);
}
function renderTikzDiagram(el, result) {
  if (!result.ok || !result.dataUrl || !result.svgText) {
    return;
  }
  el.empty();
  const block = el.createDiv({ cls: "tikzjax-hebrew-local-block" });
  const toolbar = block.createDiv({ cls: "tikzjax-hebrew-local-toolbar" });
  const exportButton = toolbar.createEl("button", {
    text: "Export SVG",
    cls: "tikzjax-hebrew-local-toolbar-button"
  });
  exportButton.addEventListener("click", () => {
    downloadSvg(result.svgText);
    new import_obsidian.Notice("SVG exported.");
  });
  const copyButton = toolbar.createEl("button", {
    text: "Copy SVG",
    cls: "tikzjax-hebrew-local-toolbar-button"
  });
  copyButton.addEventListener("click", () => __async(this, null, function* () {
    try {
      yield navigator.clipboard.writeText(result.svgText);
      new import_obsidian.Notice("SVG copied.");
    } catch (e) {
      new import_obsidian.Notice("Could not copy SVG.");
    }
  }));
  const container = block.createDiv({ cls: "tikzjax-hebrew-local-output" });
  const img = container.createEl("img");
  img.setAttr("src", result.dataUrl);
  img.setAttr("alt", "TikZ diagram");
  img.addClass("tikzjax-hebrew-local-image");
}

// latexErrorMapping.ts
var LATEX_LINE_PATTERN = /(?:^|\n)\s*l\.(\d+)/;
function getUserSourceLineOffset(wrapperPrefix) {
  if (!wrapperPrefix) {
    return 0;
  }
  return wrapperPrefix.split("\n").length;
}
function parseLatexErrorLine(raw) {
  const match = raw.match(LATEX_LINE_PATTERN);
  if (!match) {
    return null;
  }
  const line = parseInt(match[1], 10);
  return Number.isFinite(line) ? line : null;
}
function extractUsefulLatexError(raw) {
  const lines = raw.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  const bangLine = lines.find((line) => line.startsWith("! "));
  if (bangLine) {
    return bangLine.replace(/^!\s*/, "").trim();
  }
  const usefulLine = lines.find((line) => line.includes("Undefined control sequence") || line.includes("Missing") || line.includes("Runaway argument") || line.includes("Fatal error"));
  if (usefulLine) {
    return usefulLine.trim();
  }
  return "Syntax error";
}
function mapTidiedLineToNoteLine(blockStartLine, blockEndLine, getLineText, tidiedLine) {
  let nonEmptyIndex = 0;
  for (let line = blockStartLine + 1; line < blockEndLine; line++) {
    const text = getLineText(line).trim();
    if (!text) {
      continue;
    }
    nonEmptyIndex++;
    if (nonEmptyIndex === tidiedLine) {
      return line + 1;
    }
  }
  return null;
}
function formatLatexErrorWithLineMapping(raw, tidiedSource, sourceLineOffset, noteLineMapper) {
  var _a, _b;
  const usefulError = extractUsefulLatexError(raw);
  const latexLine = parseLatexErrorLine(raw);
  if (latexLine === null || latexLine <= sourceLineOffset) {
    return { message: usefulError };
  }
  const userLine = latexLine - sourceLineOffset;
  const sourceLines = tidiedSource.split("\n");
  const lineContent = (_a = sourceLines[userLine - 1]) == null ? void 0 : _a.trim();
  const noteLine = (_b = noteLineMapper == null ? void 0 : noteLineMapper(userLine)) != null ? _b : void 0;
  const snippet = lineContent ? lineContent.length > 80 ? `${lineContent.slice(0, 77)}...` : lineContent : usefulError;
  if (noteLine !== void 0) {
    return {
      message: `Line ${noteLine}: ${snippet}`,
      userLine,
      lineContent,
      noteLine
    };
  }
  return {
    message: `Line ${userLine}: ${snippet}`,
    userLine,
    lineContent
  };
}

// simpleShapes.ts
var SIMPLE_TIKZ_HELPERS = String.raw`
% logic gate scaling
\tikzset{
  every and gate US/.append style={transform shape},
  every or gate US/.append style={transform shape},
  every not gate US/.append style={transform shape},
  every nand gate US/.append style={transform shape},
  every nor gate US/.append style={transform shape},
  every xor gate US/.append style={transform shape},
  every xnor gate US/.append style={transform shape},
  every buffer gate US/.append style={transform shape},
}

% shapes
\def\Circle(#1,#2,#3){\draw (#1,#2) circle (#3);}
\def\FilledCircle(#1,#2,#3){\fill (#1,#2) circle (#3);}
\def\Point(#1,#2){\fill (#1,#2) circle (1.7pt);}
\def\Line(#1,#2,#3,#4){\draw (#1,#2) -- (#3,#4);}
\def\Arrow(#1,#2,#3,#4){\draw[->] (#1,#2) -- (#3,#4);}
\def\DArrow(#1,#2,#3,#4){\draw[<->] (#1,#2) -- (#3,#4);}
\def\DashedLine(#1,#2,#3,#4){\draw[dashed] (#1,#2) -- (#3,#4);}
\def\DottedLine(#1,#2,#3,#4){\draw[dotted] (#1,#2) -- (#3,#4);}
\def\HLine(#1,#2,#3){\draw (#1,#3) -- (#2,#3);}
\def\VLine(#1,#2,#3){\draw (#3,#1) -- (#3,#2);}
\def\Rect(#1,#2,#3,#4){\draw (#1,#2) rectangle (#3,#4);}
\def\FilledRect(#1,#2,#3,#4){\fill (#1,#2) rectangle (#3,#4);}
\def\RoundedRect(#1,#2,#3,#4){\draw[rounded corners] (#1,#2) rectangle (#3,#4);}
\def\FilledRoundedRect(#1,#2,#3,#4){\fill[rounded corners] (#1,#2) rectangle (#3,#4);}
\def\Ellipse(#1,#2,#3,#4){\draw (#1,#2) ellipse (#3 and #4);}
\def\FilledEllipse(#1,#2,#3,#4){\fill (#1,#2) ellipse (#3 and #4);}
\def\Cross(#1,#2,#3){
\draw (#1-#3,#2) -- (#1+#3,#2);
\draw (#1,#2-#3) -- (#1,#2+#3);
}
\def\Diamond(#1,#2,#3,#4){
\draw (#1,#2+#4) -- (#1+#3,#2) -- (#1,#2-#4) -- (#1-#3,#2) -- cycle;
}
\def\FilledDiamond(#1,#2,#3,#4){
\fill (#1,#2+#4) -- (#1+#3,#2) -- (#1,#2-#4) -- (#1-#3,#2) -- cycle;
}
\def\Arc(#1,#2,#3,#4,#5){\draw (#1,#2) arc (#4:#5:#3);}
\def\RightAngle(#1,#2,#3){
\draw (#1,#2+#3) -- (#1,#2) -- (#1+#3,#2);
}
\def\Grid(#1,#2,#3,#4,#5){
\draw[step=#5] (#1,#2) grid (#3,#4);
}
\def\Axis(#1,#2,#3,#4){
\draw[->] (#1,0) -- (#2,0) node[right] {$x$};
\draw[->] (0,#3) -- (0,#4) node[above] {$y$};
}
\def\AxisNamed(#1,#2,#3,#4,#5,#6){
\draw[->] (#1,0) -- (#2,0) node[right] {#5};
\draw[->] (0,#3) -- (0,#4) node[above] {#6};
}

% text
\def\Text(#1,#2,#3){\node[transform shape] at (#1,#2) {#3};}
\def\SmallText(#1,#2,#3){\node[font=\small, transform shape] at (#1,#2) {#3};}
\def\TinyText(#1,#2,#3){\node[font=\tiny, transform shape] at (#1,#2) {#3};}
\def\TextAbove(#1,#2,#3){\node[above, transform shape] at (#1,#2) {#3};}
\def\TextBelow(#1,#2,#3){\node[below, transform shape] at (#1,#2) {#3};}
\def\TextLeft(#1,#2,#3){\node[left, transform shape] at (#1,#2) {#3};}
\def\TextRight(#1,#2,#3){\node[right, transform shape] at (#1,#2) {#3};}

% gates
\def\ANDgate(#1,#2,#3){
\node[and gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\ORgate(#1,#2,#3){
\node[or gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\NOTgate(#1,#2,#3){
\node[not gate US, draw, anchor=input, transform shape] (#3) at (#1,#2) {};
}

\def\BUFFERgate(#1,#2,#3){
\node[buffer gate US, draw, anchor=input, transform shape] (#3) at (#1,#2) {};
}

\def\NANDgate(#1,#2,#3){
\node[nand gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\NORgate(#1,#2,#3){
\node[nor gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\XORgate(#1,#2,#3){
\node[xor gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\XNORgate(#1,#2,#3){
\node[xnor gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

% wires
\def\LogicWire(#1,#2){
\draw (#1) -- ++(0.35,0) |- (#2);
}

\def\LogicWireArrow(#1,#2){
\draw[->] (#1) -- ++(0.35,0) |- (#2);
}

\def\LogicWireDirect(#1,#2){
\draw (#1) -- (#2);
}

\def\LogicWireFrom(#1,#2,#3){
\draw (#1,#2) -- ++(0.35,0) |- (#3);
}

\def\LogicWireFromArrow(#1,#2,#3){
\draw[->] (#1,#2) -- ++(0.35,0) |- (#3);
}

\def\LogicWireTo(#1,#2,#3){
\draw (#1) -- ++(0.35,0) |- (#2,#3);
}

\def\LogicWireToArrow(#1,#2,#3){
\draw[->] (#1) -- ++(0.35,0) |- (#2,#3);
}

\def\Triangle(#1,#2,#3,#4,#5,#6){
\draw (#1,#2) -- (#3,#4) -- (#5,#6) -- cycle;
}

\def\FilledTriangle(#1,#2,#3,#4,#5,#6){
\fill (#1,#2) -- (#3,#4) -- (#5,#6) -- cycle;
}

% circuit symbols
\def\Resistor(#1,#2,#3,#4){
\draw (#1,#2) -- ++(0.15,0);
\draw (#1+0.15,#2-#4/2) rectangle ++(#3-0.3,#4);
\draw (#1+#3-0.15,#2) -- ++(0.15,0);
}

\def\Capacitor(#1,#2,#3,#4){
\draw (#1,#2) -- ++(0.15,0);
\draw (#1+0.15,#2-#4) -- (#1+0.15,#2+#4);
\draw (#1+0.15+#3,#2-#4) -- (#1+0.15+#3,#2+#4);
\draw (#1+0.15+#3,#2) -- ++(0.15,0);
}

\def\Ground(#1,#2,#3){
\draw (#1,#2) -- (#1,#2-#3);
\draw (#1-0.25,#2-#3) -- (#1+0.25,#2-#3);
\draw (#1-0.15,#2-#3-0.12) -- (#1+0.15,#2-#3-0.12);
\draw (#1-0.08,#2-#3-0.24) -- (#1+0.08,#2-#3-0.24);
}

\def\VSource(#1,#2,#3,#4){
\draw (#1,#2) circle (#3);
\node[transform shape] at (#1,#2) {$#4$};
}
`;

// tikzSource.ts
var DOCUMENTCLASS_LINE = "\\documentclass[tikz,border=5pt]{standalone}\n";
var LATEX_WRAPPER_PREFIX = `${DOCUMENTCLASS_LINE}\\usepackage{fontspec}
\\usepackage{polyglossia}

\\setmainlanguage{english}
\\setotherlanguage{hebrew}

\\newfontfamily\\hebrewfont[Script=Hebrew]{David CLM}
\\newfontfamily\\hebrewfontsf[Script=Hebrew]{David CLM}
\\newfontfamily\\hebrewfonttt[Script=Hebrew]{David CLM}

\\usepackage{tikz}
\\usetikzlibrary{arrows.meta,positioning,calc,shapes,decorations.pathmorphing,shapes.gates.logic.US}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{circuitikz}
\\usepackage{pgfplots}
\\pgfplotsset{compat=1.18}

\\newcommand{\\he}[1]{\\texthebrew{#1}}
${SIMPLE_TIKZ_HELPERS}
\\begin{document}
`;
var LATEX_WRAPPER_SUFFIX = `
\\end{document}
`;
var USER_SOURCE_LINE_OFFSET = getUserSourceLineOffset(LATEX_WRAPPER_PREFIX);
function tidyTikzSource(tikzSource) {
  return tikzSource.replaceAll("&nbsp;", "").split("\n").map((line) => line.trim()).filter(Boolean).join("\n");
}
function wrapLatexSource(source) {
  let cleanedSource = source;
  cleanedSource = cleanedSource.replace(/\\documentclass(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\usepackage(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\pgfplotsset\{[^}]*\}/g, "");
  cleanedSource = cleanedSource.replace(/\\begin\{document\}/g, "");
  cleanedSource = cleanedSource.replace(/\\end\{document\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setmainlanguage\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setotherlanguage\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setmainfont(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setsansfont(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\newfontfamily\\\w+(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  return LATEX_WRAPPER_PREFIX + cleanedSource.trim() + LATEX_WRAPPER_SUFFIX;
}

// inlinePreview.ts
function getCurrentTikzBlock(editor) {
  const cursor = editor.getCursor();
  let startLine = -1;
  for (let line = cursor.line; line >= 0; line--) {
    const text = editor.getLine(line).trim();
    if (text.startsWith("```tikz")) {
      startLine = line;
      break;
    }
    if (text === "```") {
      return null;
    }
  }
  if (startLine === -1) {
    return null;
  }
  let endLine = -1;
  for (let line = startLine + 1; line < editor.lineCount(); line++) {
    if (editor.getLine(line).trim() === "```") {
      endLine = line;
      break;
    }
  }
  if (endLine === -1 || cursor.line <= startLine || cursor.line >= endLine) {
    return null;
  }
  return {
    source: editor.getRange({ line: startLine + 1, ch: 0 }, { line: endLine, ch: 0 }),
    startLine,
    endLine
  };
}
var InlinePreviewManager = class {
  constructor(getActiveMarkdownView, renderer) {
    this.getActiveMarkdownView = getActiveMarkdownView;
    this.renderer = renderer;
    this.enabled = false;
    this.container = null;
    this.timer = null;
    this.lastGoodDataUrl = null;
    this.lastSource = null;
    this.renderToken = 0;
  }
  enable(initialDelayMs = 0) {
    this.enabled = true;
    this.scheduleUpdate(initialDelayMs);
  }
  disable() {
    this.enabled = false;
    this.lastGoodDataUrl = null;
    this.lastSource = null;
    this.clearTimer();
    if (this.container) {
      this.container.remove();
      this.container = null;
    }
  }
  scheduleUpdate(delay = 800) {
    if (!this.enabled) {
      return;
    }
    this.clearTimer();
    this.timer = window.setTimeout(() => {
      void this.updateFromActiveEditor();
    }, delay);
  }
  clearTimer() {
    if (this.timer) {
      window.clearTimeout(this.timer);
      this.timer = null;
    }
  }
  hide() {
    if (this.container) {
      this.container.remove();
      this.container = null;
    }
  }
  containerEl(view) {
    if (this.container && document.body.contains(this.container)) {
      return this.container;
    }
    this.container = view.containerEl.createDiv({
      cls: "tikzjax-hebrew-local-inline-preview"
    });
    return this.container;
  }
  showMessage(view, message) {
    const el = this.containerEl(view);
    el.empty();
    el.createDiv({
      cls: "tikzjax-hebrew-local-inline-preview-message",
      text: message
    });
  }
  showImage(view, dataUrl) {
    const el = this.containerEl(view);
    el.empty();
    const output = el.createDiv({ cls: "tikzjax-hebrew-local-output" });
    const img = output.createEl("img");
    img.setAttr("src", dataUrl);
    img.setAttr("alt", "TikZ diagram");
    img.addClass("tikzjax-hebrew-local-image");
  }
  showError(view, message, details, onRetry) {
    appendTikzError(this.containerEl(view), message, details, onRetry, "tikzjax-hebrew-local-inline-preview-error");
  }
  updateFromActiveEditor() {
    return __async(this, null, function* () {
      var _a;
      if (!this.enabled) {
        return;
      }
      const view = this.getActiveMarkdownView();
      if (!view) {
        this.hide();
        return;
      }
      const block = getCurrentTikzBlock(view.editor);
      if (!block) {
        this.hide();
        return;
      }
      const source = tidyTikzSource(block.source);
      if (!source.trim()) {
        this.showMessage(view, "Nothing to render.");
        return;
      }
      if (source === this.lastSource && this.lastGoodDataUrl) {
        return;
      }
      const token = ++this.renderToken;
      if (!this.lastGoodDataUrl) {
        this.showMessage(view, "Rendering\u2026");
      }
      const result = yield this.renderer.renderToSvg(source, {
        block,
        editor: view.editor
      });
      if (token !== this.renderToken) {
        return;
      }
      if (result.ok && result.dataUrl) {
        this.lastSource = source;
        this.lastGoodDataUrl = result.dataUrl;
        this.showImage(view, result.dataUrl);
        return;
      }
      const retry = result.timedOut ? () => {
        this.lastSource = null;
        void this.updateFromActiveEditor();
      } : void 0;
      if (this.lastGoodDataUrl) {
        this.showImage(view, this.lastGoodDataUrl);
      } else {
        this.containerEl(view).empty();
      }
      this.showError(view, (_a = result.error) != null ? _a : "Render failed.", result.rawLog, retry);
    });
  }
};

// latexAutocomplete.ts
var import_autocomplete = __toModule(require("@codemirror/autocomplete"));
var latexCommands = [
  (0, import_autocomplete.snippetCompletion)(String.raw`\begin\{tikzpicture\}
\${}
\end\{tikzpicture\}`, {
    label: "\\begin{tikzpicture}",
    type: "keyword",
    detail: "TikZ environment"
  }),
  {
    label: "\\end{tikzpicture}",
    type: "keyword",
    apply: "\\end{tikzpicture}",
    detail: "End TikZ environment"
  },
  (0, import_autocomplete.snippetCompletion)(String.raw`\begin\{axis\}
\${}
\end\{axis\}`, {
    label: "\\begin{axis}",
    type: "keyword",
    detail: "Pgfplots axis environment"
  }),
  {
    label: "\\end{axis}",
    type: "keyword",
    apply: "\\end{axis}",
    detail: "End axis environment"
  },
  {
    label: "\\draw",
    type: "function",
    apply: "\\draw ",
    detail: "TikZ draw command"
  },
  {
    label: "\\fill",
    type: "function",
    apply: "\\fill ",
    detail: "Fill a path"
  },
  {
    label: "\\filldraw",
    type: "function",
    apply: "\\filldraw ",
    detail: "Fill and stroke a path"
  },
  {
    label: "\\path",
    type: "function",
    apply: "\\path ",
    detail: "TikZ path without drawing"
  },
  {
    label: "\\node",
    type: "function",
    apply: "\\node ",
    detail: "TikZ node command"
  },
  {
    label: "\\coordinate",
    type: "function",
    apply: "\\coordinate ",
    detail: "Named coordinate"
  },
  {
    label: "\\clip",
    type: "function",
    apply: "\\clip ",
    detail: "Clip to a path"
  },
  (0, import_autocomplete.snippetCompletion)(String.raw`\foreach \x in \{1,...,5\} \{
  \${}
\}`, {
    label: "\\foreach",
    type: "function",
    detail: "Loop over values"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\scope
\${}
\endscope`, {
    label: "\\scope",
    type: "function",
    detail: "Local TikZ scope"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\tikzset\{\${}\}`, {
    label: "\\tikzset",
    type: "function",
    detail: "Set TikZ styles"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\usetikzlibrary\{\${}\}`, {
    label: "\\usetikzlibrary",
    type: "function",
    detail: "Load TikZ library"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\he\{\${}\}`, {
    label: "\\he{}",
    type: "function",
    detail: "Hebrew text wrapper"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\text\{\${}\}`, {
    label: "\\text{}",
    type: "function",
    detail: "Text in math mode"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\frac\{\${1}\}\{\${2}\}`, {
    label: "\\frac{}{}",
    type: "function",
    detail: "Fraction"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\cfrac\{\${1}\}\{\${2}\}`, {
    label: "\\cfrac{}{}",
    type: "function",
    detail: "Display fraction"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\sqrt\{\${}\}`, {
    label: "\\sqrt{}",
    type: "function",
    detail: "Square root"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\sum_\{\${1}\}\^\{\${2}\}`, {
    label: "\\sum_{}^{}",
    type: "function",
    detail: "Summation"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\int_\{\${1}\}\^\{\${2}\}`, {
    label: "\\int_{}^{}",
    type: "function",
    detail: "Integral"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\lim_\{\${}\}`, {
    label: "\\lim_{}",
    type: "function",
    detail: "Limit"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\vec\{\${}\}`, {
    label: "\\vec{}",
    type: "function",
    detail: "Vector arrow"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\hat\{\${}\}`, {
    label: "\\hat{}",
    type: "function",
    detail: "Hat accent"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\bar\{\${}\}`, {
    label: "\\bar{}",
    type: "function",
    detail: "Bar accent"
  }),
  {
    label: "\\alpha",
    type: "variable",
    apply: "\\alpha",
    detail: "Greek letter"
  },
  {
    label: "\\beta",
    type: "variable",
    apply: "\\beta",
    detail: "Greek letter"
  },
  {
    label: "\\gamma",
    type: "variable",
    apply: "\\gamma",
    detail: "Greek letter"
  },
  {
    label: "\\delta",
    type: "variable",
    apply: "\\delta",
    detail: "Greek letter"
  },
  {
    label: "\\Delta",
    type: "variable",
    apply: "\\Delta",
    detail: "Greek letter"
  },
  {
    label: "\\theta",
    type: "variable",
    apply: "\\theta",
    detail: "Greek letter"
  },
  {
    label: "\\lambda",
    type: "variable",
    apply: "\\lambda",
    detail: "Greek letter"
  },
  {
    label: "\\mu",
    type: "variable",
    apply: "\\mu",
    detail: "Greek letter"
  },
  {
    label: "\\pi",
    type: "variable",
    apply: "\\pi",
    detail: "Greek letter"
  },
  {
    label: "\\sigma",
    type: "variable",
    apply: "\\sigma",
    detail: "Greek letter"
  },
  {
    label: "\\omega",
    type: "variable",
    apply: "\\omega",
    detail: "Greek letter"
  },
  {
    label: "\\Omega",
    type: "variable",
    apply: "\\Omega",
    detail: "Greek letter"
  },
  {
    label: "\\infty",
    type: "variable",
    apply: "\\infty",
    detail: "Infinity symbol"
  },
  {
    label: "\\partial",
    type: "variable",
    apply: "\\partial",
    detail: "Partial derivative"
  },
  {
    label: "\\nabla",
    type: "variable",
    apply: "\\nabla",
    detail: "Nabla operator"
  },
  {
    label: "\\cdot",
    type: "variable",
    apply: "\\cdot",
    detail: "Multiplication dot"
  },
  {
    label: "\\times",
    type: "variable",
    apply: "\\times",
    detail: "Multiplication cross"
  },
  {
    label: "\\pm",
    type: "variable",
    apply: "\\pm",
    detail: "Plus/minus"
  },
  {
    label: "\\leq",
    type: "variable",
    apply: "\\leq",
    detail: "Less than or equal"
  },
  {
    label: "\\geq",
    type: "variable",
    apply: "\\geq",
    detail: "Greater than or equal"
  },
  {
    label: "\\neq",
    type: "variable",
    apply: "\\neq",
    detail: "Not equal"
  },
  {
    label: "\\approx",
    type: "variable",
    apply: "\\approx",
    detail: "Approximately equal"
  }
];
var simpleShapeHelpers = [
  { label: "\\Circle(,,)", apply: "\\Circle(0,0,1)", detail: "Circle outline" },
  { label: "\\FilledCircle(,,)", apply: "\\FilledCircle(0,0,1)", detail: "Filled circle" },
  { label: "\\Point(,)", apply: "\\Point(0,0)", detail: "Small point" },
  { label: "\\Line(,,,)", apply: "\\Line(0,0,1,1)", detail: "Line segment" },
  { label: "\\Arrow(,,,)", apply: "\\Arrow(0,0,1,1)", detail: "Arrow" },
  { label: "\\DArrow(,,,)", apply: "\\DArrow(0,0,1,1)", detail: "Double arrow" },
  { label: "\\DashedLine(,,,)", apply: "\\DashedLine(0,0,1,1)", detail: "Dashed line" },
  { label: "\\DottedLine(,,,)", apply: "\\DottedLine(0,0,1,1)", detail: "Dotted line" },
  { label: "\\HLine(,,)", apply: "\\HLine(0,1,0)", detail: "Horizontal line" },
  { label: "\\VLine(,,)", apply: "\\VLine(0,1,0)", detail: "Vertical line" },
  { label: "\\Rect(,,,)", apply: "\\Rect(0,0,1,1)", detail: "Rectangle outline" },
  { label: "\\FilledRect(,,,)", apply: "\\FilledRect(0,0,1,1)", detail: "Filled rectangle" },
  { label: "\\RoundedRect(,,,)", apply: "\\RoundedRect(0,0,1,1)", detail: "Rounded rectangle" },
  { label: "\\FilledRoundedRect(,,,)", apply: "\\FilledRoundedRect(0,0,1,1)", detail: "Filled rounded rectangle" },
  { label: "\\Ellipse(,,,)", apply: "\\Ellipse(0,0,1,0.5)", detail: "Ellipse outline" },
  { label: "\\FilledEllipse(,,,)", apply: "\\FilledEllipse(0,0,1,0.5)", detail: "Filled ellipse" },
  { label: "\\Cross(,,)", apply: "\\Cross(0,0,0.2)", detail: "Cross marker" },
  { label: "\\Diamond(,,,)", apply: "\\Diamond(0,0,0.5,0.3)", detail: "Diamond outline" },
  { label: "\\FilledDiamond(,,,)", apply: "\\FilledDiamond(0,0,0.5,0.3)", detail: "Filled diamond" },
  { label: "\\Arc(,,,,)", apply: "\\Arc(0,0,1,0,90)", detail: "Circular arc" },
  { label: "\\RightAngle(,,)", apply: "\\RightAngle(0,0,0.2)", detail: "Right-angle mark" },
  { label: "\\Grid(,,,,)", apply: "\\Grid(0,0,3,3,0.5)", detail: "Grid" },
  { label: "\\Triangle(,,,,,)", apply: "\\Triangle(0,0,1,0,0.5,1)", detail: "Triangle outline" },
  { label: "\\FilledTriangle(,,,,,)", apply: "\\FilledTriangle(0,0,1,0,0.5,1)", detail: "Filled triangle" },
  { label: "\\Axis(,,,)", apply: "\\Axis(-1,3,-1,3)", detail: "XY axes with labels" },
  { label: "\\AxisNamed(,,,,,)", apply: "\\AxisNamed(-1,3,-1,3,x,y)", detail: "Named axes" },
  { label: "\\Text(,,)", apply: "\\Text(0,0,text)", detail: "Text node" },
  { label: "\\SmallText(,,)", apply: "\\SmallText(0,0,text)", detail: "Small text node" },
  { label: "\\TinyText(,,)", apply: "\\TinyText(0,0,text)", detail: "Tiny text node" },
  { label: "\\TextAbove(,,)", apply: "\\TextAbove(0,0,text)", detail: "Text above point" },
  { label: "\\TextBelow(,,)", apply: "\\TextBelow(0,0,text)", detail: "Text below point" },
  { label: "\\TextLeft(,,)", apply: "\\TextLeft(0,0,text)", detail: "Text left of point" },
  { label: "\\TextRight(,,)", apply: "\\TextRight(0,0,text)", detail: "Text right of point" },
  { label: "\\Resistor(,,,)", apply: "\\Resistor(0,0,1,0.3)", detail: "Resistor symbol" },
  { label: "\\Capacitor(,,,)", apply: "\\Capacitor(0,0,0.4,0.3)", detail: "Capacitor symbol" },
  { label: "\\Ground(,,)", apply: "\\Ground(0,0,0.5)", detail: "Ground symbol" },
  { label: "\\VSource(,,,)", apply: "\\VSource(0,0,0.3,V)", detail: "Voltage source" },
  { label: "\\ANDgate(,,)", apply: "\\ANDgate(0,0,and1)", detail: "AND gate" },
  { label: "\\ORgate(,,)", apply: "\\ORgate(0,0,or1)", detail: "OR gate" },
  { label: "\\NOTgate(,,)", apply: "\\NOTgate(0,0,not1)", detail: "NOT gate" },
  { label: "\\NANDgate(,,)", apply: "\\NANDgate(0,0,nand1)", detail: "NAND gate" },
  { label: "\\NORgate(,,)", apply: "\\NORgate(0,0,nor1)", detail: "NOR gate" },
  { label: "\\XORgate(,,)", apply: "\\XORgate(0,0,xor1)", detail: "XOR gate" },
  { label: "\\XNORgate(,,)", apply: "\\XNORgate(0,0,xnor1)", detail: "XNOR gate" },
  { label: "\\BUFFERgate(,,)", apply: "\\BUFFERgate(0,0,buffer1)", detail: "Buffer gate" },
  { label: "\\LogicWire(,)", apply: "\\LogicWire(a,b)", detail: "Orthogonal wire" },
  { label: "\\LogicWireArrow(,)", apply: "\\LogicWireArrow(a,b)", detail: "Wire with arrow" },
  { label: "\\LogicWireDirect(,)", apply: "\\LogicWireDirect(a,b)", detail: "Direct wire" },
  { label: "\\LogicWireFrom(,,)", apply: "\\LogicWireFrom(0,0,a)", detail: "Wire from coordinate" },
  { label: "\\LogicWireFromArrow(,,)", apply: "\\LogicWireFromArrow(0,0,a)", detail: "Arrow wire from coordinate" },
  { label: "\\LogicWireTo(,,)", apply: "\\LogicWireTo(a,0,0)", detail: "Wire to coordinate" },
  { label: "\\LogicWireToArrow(,,)", apply: "\\LogicWireToArrow(a,0,0)", detail: "Arrow wire to coordinate" }
];
var tikzOptions = [
  { label: "->", type: "property", apply: "->", detail: "Arrow tip" },
  { label: "<-", type: "property", apply: "<-", detail: "Reverse arrow tip" },
  { label: "<->", type: "property", apply: "<->", detail: "Double arrow" },
  { label: "-Stealth", type: "property", apply: "-Stealth", detail: "Stealth arrow" },
  { label: "Stealth-Stealth", type: "property", apply: "Stealth-Stealth", detail: "Stealth both ends" },
  { label: "thick", type: "property", apply: "thick", detail: "Thick line" },
  { label: "very thick", type: "property", apply: "very thick", detail: "Very thick line" },
  { label: "thin", type: "property", apply: "thin", detail: "Thin line" },
  { label: "dashed", type: "property", apply: "dashed", detail: "Dashed line" },
  { label: "dotted", type: "property", apply: "dotted", detail: "Dotted line" },
  { label: "line width=1pt", type: "property", apply: "line width=1pt", detail: "Line width" },
  { label: "rounded corners", type: "property", apply: "rounded corners", detail: "Rounded corners" },
  { label: "circle", type: "property", apply: "circle", detail: "Circle shape" },
  { label: "rectangle", type: "property", apply: "rectangle", detail: "Rectangle shape" },
  { label: "ellipse", type: "property", apply: "ellipse", detail: "Ellipse shape" },
  { label: "draw=black", type: "property", apply: "draw=black", detail: "Stroke color" },
  { label: "fill=cyan!10", type: "property", apply: "fill=cyan!10", detail: "Fill color" },
  { label: "fill=blue!20", type: "property", apply: "fill=blue!20", detail: "Light blue fill" },
  { label: "fill=red!20", type: "property", apply: "fill=red!20", detail: "Light red fill" },
  { label: "fill=green!20", type: "property", apply: "fill=green!20", detail: "Light green fill" },
  { label: "fill=none", type: "property", apply: "fill=none", detail: "No fill" },
  { label: "opacity=0.5", type: "property", apply: "opacity=0.5", detail: "Opacity" },
  { label: "font=\\small", type: "property", apply: "font=\\small", detail: "Small font" },
  { label: "font=\\tiny", type: "property", apply: "font=\\tiny", detail: "Tiny font" },
  { label: "align=center", type: "property", apply: "align=center", detail: "Centered text" },
  { label: "align=left", type: "property", apply: "align=left", detail: "Left-aligned text" },
  { label: "align=right", type: "property", apply: "align=right", detail: "Right-aligned text" },
  { label: "anchor=north", type: "property", apply: "anchor=north", detail: "North anchor" },
  { label: "anchor=south", type: "property", apply: "anchor=south", detail: "South anchor" },
  { label: "anchor=east", type: "property", apply: "anchor=east", detail: "East anchor" },
  { label: "anchor=west", type: "property", apply: "anchor=west", detail: "West anchor" },
  { label: "inner sep=2pt", type: "property", apply: "inner sep=2pt", detail: "Inner padding" },
  { label: "outer sep=0pt", type: "property", apply: "outer sep=0pt", detail: "Outer padding" },
  { label: "minimum width=1cm", type: "property", apply: "minimum width=1cm", detail: "Minimum width" },
  { label: "minimum height=1cm", type: "property", apply: "minimum height=1cm", detail: "Minimum height" },
  { label: "scale=0.8", type: "property", apply: "scale=0.8", detail: "Scale factor" },
  { label: "rotate=45", type: "property", apply: "rotate=45", detail: "Rotation" },
  { label: "xshift=1cm", type: "property", apply: "xshift=1cm", detail: "Horizontal shift" },
  { label: "yshift=1cm", type: "property", apply: "yshift=1cm", detail: "Vertical shift" },
  { label: "below=of", type: "property", apply: "below=of ", detail: "Position below node" },
  { label: "right=of", type: "property", apply: "right=of ", detail: "Position right of node" },
  { label: "above=of", type: "property", apply: "above=of ", detail: "Position above node" },
  { label: "left=of", type: "property", apply: "left=of ", detail: "Position left of node" }
];
var tikzLibraries = [
  { label: "arrows.meta", type: "text", apply: "arrows.meta", detail: "Arrow tips" },
  { label: "positioning", type: "text", apply: "positioning", detail: "Relative positioning" },
  { label: "calc", type: "text", apply: "calc", detail: "Coordinate calculations" },
  { label: "shapes", type: "text", apply: "shapes", detail: "Extra shapes" },
  { label: "decorations.pathmorphing", type: "text", apply: "decorations.pathmorphing", detail: "Path decorations" },
  { label: "shapes.gates.logic.US", type: "text", apply: "shapes.gates.logic.US", detail: "Logic gates" },
  { label: "matrix", type: "text", apply: "matrix", detail: "Matrix layouts" },
  { label: "fit", type: "text", apply: "fit", detail: "Fit nodes around content" },
  { label: "backgrounds", type: "text", apply: "backgrounds", detail: "Background layers" }
];
var allCommandCompletions = [...latexCommands, ...simpleShapeHelpers];
function insideLatexOrTikzBlock(textBeforeCursor) {
  const fencePattern = /```(?:tikz|latex|lualatex|tex)\b/g;
  let lastOpen = -1;
  let match;
  while ((match = fencePattern.exec(textBeforeCursor)) !== null) {
    lastOpen = match.index;
  }
  if (lastOpen === -1) {
    return false;
  }
  const afterOpen = textBeforeCursor.slice(lastOpen);
  const lines = afterOpen.split("\n");
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === "```") {
      return false;
    }
  }
  return true;
}
function filterCompletions(options, prefix) {
  const lowerPrefix = prefix.toLowerCase();
  return options.filter((option) => option.label.toLowerCase().startsWith(lowerPrefix));
}
function latexCompletionSource(context) {
  const textBeforeCursor = context.state.doc.sliceString(0, context.pos);
  if (!insideLatexOrTikzBlock(textBeforeCursor)) {
    return null;
  }
  const commandMatch = context.matchBefore(/\\(?:[A-Za-z]+|\{)?/);
  if (commandMatch) {
    const prefix = commandMatch.text;
    return {
      from: commandMatch.from,
      options: filterCompletions(allCommandCompletions, prefix),
      validFor: /^\\(?:[A-Za-z]+|\{)?$/
    };
  }
  const libraryMatch = context.matchBefore(/\\usetikzlibrary\{[^}]*\}?/);
  if (libraryMatch) {
    const openBrace = libraryMatch.text.indexOf("{");
    if (openBrace !== -1) {
      const prefix = libraryMatch.text.slice(openBrace + 1).replace(/}$/, "");
      const from = libraryMatch.from + openBrace + 1;
      return {
        from,
        options: filterCompletions(tikzLibraries, prefix),
        validFor: /^[^}]*$/
      };
    }
  }
  const bracketOptionMatch = context.matchBefore(/(?:^|[\[\s,{])([A-Za-z!\\=0-9.<>\-]+)?/);
  if (bracketOptionMatch) {
    const prefix = bracketOptionMatch.text.replace(/^[\[\s,{]+/, "");
    const charBefore = context.state.doc.sliceString(Math.max(0, context.pos - 1), context.pos);
    if (prefix.length > 0 || charBefore === "[" || charBefore === "," || context.explicit) {
      return {
        from: context.pos - prefix.length,
        options: filterCompletions(tikzOptions, prefix),
        validFor: /^[A-Za-z!\\=0-9.<>\-]*$/
      };
    }
  }
  return null;
}
function latexAutocompleteExtension() {
  return (0, import_autocomplete.autocompletion)({
    override: [latexCompletionSource],
    activateOnTyping: true,
    maxRenderedOptions: 40
  });
}

// commandResolver.ts
var import_child_process = __toModule(require("child_process"));
var fs = __toModule(require("fs"));
var RenderTimeoutError = class extends Error {
  constructor(timeoutMs) {
    super(`Timed out after ${Math.round(timeoutMs / 1e3)}s`);
    this.name = "RenderTimeoutError";
  }
};
function execFileWithTimeout(file, args, options, timeoutMs) {
  return new Promise((resolve, reject) => {
    let timedOut = false;
    const child = (0, import_child_process.execFile)(file, args, options, (err, stdout, stderr) => {
      var _a, _b;
      if (timedOut) {
        return;
      }
      clearTimeout(timer);
      if (err) {
        reject(err);
        return;
      }
      resolve({
        stdout: (_a = stdout == null ? void 0 : stdout.toString()) != null ? _a : "",
        stderr: (_b = stderr == null ? void 0 : stderr.toString()) != null ? _b : ""
      });
    });
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
      reject(new RenderTimeoutError(timeoutMs));
    }, timeoutMs);
  });
}
function resolveCommand(candidates) {
  return __async(this, null, function* () {
    for (const candidate of candidates) {
      if (candidate.includes("/")) {
        if (fs.existsSync(candidate)) {
          return candidate;
        }
        continue;
      }
      try {
        const { stdout } = yield execFileWithTimeout("/usr/bin/which", [candidate], {}, 5e3);
        const resolved = stdout.trim();
        if (resolved) {
          return resolved;
        }
      } catch (e) {
      }
    }
    return null;
  });
}
function resolveLuaLatex() {
  return __async(this, null, function* () {
    return resolveCommand([
      "/Library/TeX/texbin/lualatex",
      "/usr/local/texlive/2025/bin/universal-darwin/lualatex",
      "/usr/local/bin/lualatex",
      "lualatex"
    ]);
  });
}
function resolvePdfToCairo() {
  return __async(this, null, function* () {
    return resolveCommand([
      "/opt/homebrew/bin/pdftocairo",
      "/usr/local/bin/pdftocairo",
      "/usr/bin/pdftocairo",
      "pdftocairo"
    ]);
  });
}
function readLogTail(logPath, maxChars = 8e3) {
  if (!fs.existsSync(logPath)) {
    return "";
  }
  const log = fs.readFileSync(logPath, "utf8");
  return log.length <= maxChars ? log : `...(truncated)...
${log.slice(-maxChars)}`;
}
function formatExecError(err) {
  if (err instanceof RenderTimeoutError) {
    return err.message;
  }
  if (err instanceof Error) {
    const execErr = err;
    return [execErr.message, execErr.stdout, execErr.stderr].filter(Boolean).join("\n");
  }
  return String(err);
}

// renderer.ts
var import_crypto = __toModule(require("crypto"));
var fs2 = __toModule(require("fs"));
var os = __toModule(require("os"));
var path = __toModule(require("path"));
var RENDER_TIMEOUT_MS = 6e4;
var CACHE_MAX = 32;
var CACHE_TTL_MS = 30 * 60 * 1e3;
function cacheKey(source, invertDark) {
  return (0, import_crypto.createHash)("sha256").update(source).update(invertDark ? ":dark" : ":light").digest("hex");
}
function svgDataUrl(svgText) {
  return `data:image/svg+xml;base64,${Buffer.from(svgText, "utf8").toString("base64")}`;
}
function invertSvgForDarkMode(svg) {
  return svg.replaceAll("rgb(0%,0%,0%)", "rgb(100%,100%,100%)").replace(/rgb[(]0%,[ \t]*0%,[ \t]*0%[)]/g, "rgb(100%,100%,100%)").replace(/rgb[(]0,[ \t]*0,[ \t]*0[)]/g, "rgb(255,255,255)").replace(/#000000(?![0-9a-f])/gi, "#ffffff").replace(/#000(?![0-9a-f])/gi, "#fff").replace(/stroke:[ \t]*black/gi, "stroke:white").replace(/fill:[ \t]*black/gi, "fill:white").replace(/stroke="black"/gi, 'stroke="white"').replace(/fill="black"/gi, 'fill="white"');
}
var TikzRenderer = class {
  constructor(invertInDarkMode) {
    this.invertInDarkMode = invertInDarkMode;
    this.cache = new Map();
    this.inFlight = new Map();
  }
  renderToSvg(source, errorContext) {
    return __async(this, null, function* () {
      const invertDark = this.invertInDarkMode() && document.body.classList.contains("theme-dark");
      const key = cacheKey(source, invertDark);
      const hit = this.cache.get(key);
      if (hit && Date.now() - hit.createdAt <= CACHE_TTL_MS) {
        this.cache.delete(key);
        this.cache.set(key, hit);
        return { ok: true, svgText: hit.svgText, dataUrl: svgDataUrl(hit.svgText) };
      }
      if (hit) {
        this.cache.delete(key);
      }
      const pending = this.inFlight.get(key);
      if (pending) {
        return pending;
      }
      const renderPromise = this.compile(source, errorContext, invertDark, key).finally(() => this.inFlight.delete(key));
      this.inFlight.set(key, renderPromise);
      return renderPromise;
    });
  }
  clearCache() {
    this.cache.clear();
    this.inFlight.clear();
  }
  latexError(rawError, source, errorContext, timedOut = false) {
    const noteLineMapper = (errorContext == null ? void 0 : errorContext.block) && errorContext.editor ? (userLine) => mapTidiedLineToNoteLine(errorContext.block.startLine, errorContext.block.endLine, (line) => errorContext.editor.getLine(line), userLine) : void 0;
    const mapped = formatLatexErrorWithLineMapping(rawError, source, USER_SOURCE_LINE_OFFSET, noteLineMapper);
    return {
      ok: false,
      error: timedOut ? "Timed out." : mapped.message,
      rawLog: rawError,
      userLine: mapped.userLine,
      noteLine: mapped.noteLine,
      lineContent: mapped.lineContent,
      timedOut
    };
  }
  remember(key, svgText) {
    if (this.cache.has(key)) {
      this.cache.delete(key);
    }
    this.cache.set(key, { svgText, createdAt: Date.now() });
    while (this.cache.size > CACHE_MAX) {
      const oldest = this.cache.keys().next().value;
      if (oldest === void 0) {
        break;
      }
      this.cache.delete(oldest);
    }
  }
  compile(source, errorContext, invertDark, key) {
    return __async(this, null, function* () {
      const tmpDir = fs2.mkdtempSync(path.join(os.tmpdir(), "obsidian-tikz-"));
      const texPath = path.join(tmpDir, "diagram.tex");
      const pdfPath = path.join(tmpDir, "diagram.pdf");
      const logPath = path.join(tmpDir, "diagram.log");
      const svgPath = path.join(tmpDir, "diagram.svg");
      try {
        fs2.writeFileSync(texPath, wrapLatexSource(source), "utf8");
        const lualatex = yield resolveLuaLatex();
        if (!lualatex) {
          return {
            ok: false,
            error: "LuaLaTeX not found.",
            rawLog: "Expected at /Library/TeX/texbin/lualatex\nCheck: which lualatex"
          };
        }
        try {
          yield execFileWithTimeout(lualatex, [
            "-interaction=nonstopmode",
            "-halt-on-error",
            `-output-directory=${tmpDir}`,
            texPath
          ], { cwd: tmpDir, maxBuffer: 10 * 1024 * 1024 }, RENDER_TIMEOUT_MS);
        } catch (err) {
          const logTail = readLogTail(logPath);
          const raw = [formatExecError(err), logTail && `
--- log ---
${logTail}`].filter(Boolean).join("\n");
          return this.latexError(raw, source, errorContext, err instanceof RenderTimeoutError);
        }
        if (!fs2.existsSync(pdfPath)) {
          const logTail = readLogTail(logPath);
          if (logTail) {
            return this.latexError(`No PDF produced.
--- log ---
${logTail}`, source, errorContext);
          }
          return { ok: false, error: "No PDF produced.", rawLog: "LuaLaTeX exited without diagram.pdf." };
        }
        const pdftocairo = yield resolvePdfToCairo();
        if (!pdftocairo) {
          return {
            ok: false,
            error: "pdftocairo not found.",
            rawLog: "Install: brew install poppler"
          };
        }
        try {
          yield execFileWithTimeout(pdftocairo, ["-svg", pdfPath, svgPath], {
            cwd: tmpDir,
            maxBuffer: 30 * 1024 * 1024
          }, RENDER_TIMEOUT_MS);
        } catch (err) {
          return this.latexError(formatExecError(err), source, errorContext, err instanceof RenderTimeoutError);
        }
        if (!fs2.existsSync(svgPath)) {
          return { ok: false, error: "No SVG produced.", rawLog: `PDF: ${pdfPath}` };
        }
        let svgText = fs2.readFileSync(svgPath, "utf8");
        if (invertDark) {
          svgText = invertSvgForDarkMode(svgText);
        }
        this.remember(key, svgText);
        return { ok: true, svgText, dataUrl: svgDataUrl(svgText) };
      } finally {
        try {
          fs2.rmSync(tmpDir, { recursive: true, force: true });
        } catch (e) {
        }
      }
    });
  }
};

// settings.ts
var import_obsidian2 = __toModule(require("obsidian"));
var DEFAULT_SETTINGS = {
  invertColorsInDarkMode: true,
  inlineLivePreviewEnabledByDefault: true
};
var TikzjaxSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Invert colors in dark mode").setDesc("Flip black strokes/fills to white when Obsidian is in dark mode.").addToggle((toggle) => toggle.setValue(this.plugin.settings.invertColorsInDarkMode).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.invertColorsInDarkMode = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian2.Setting(containerEl).setName("Live preview by default").setDesc("Show the floating preview when the cursor is inside a tikz block.").addToggle((toggle) => toggle.setValue(this.plugin.settings.inlineLivePreviewEnabledByDefault).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.inlineLivePreviewEnabledByDefault = value;
      yield this.plugin.saveSettings();
    })));
  }
};

// main.ts
var LuaTikzPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.renderer = new TikzRenderer(() => this.settings.invertColorsInDarkMode);
      this.inlinePreview = new InlinePreviewManager(() => this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView), this.renderer);
      this.registerEditorExtension(latexAutocompleteExtension());
      this.addCommand({
        id: "toggle-tikz-inline-live-preview",
        name: "Toggle inline live preview",
        callback: () => this.toggleInlineLivePreview()
      });
      this.registerEvent(this.app.workspace.on("editor-change", () => {
        this.inlinePreview.scheduleUpdate();
      }));
      this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
        this.inlinePreview.scheduleUpdate();
      }));
      this.registerDomEvent(document, "selectionchange", () => {
        this.inlinePreview.scheduleUpdate();
      });
      this.addSettingTab(new TikzjaxSettingTab(this.app, this));
      this.addSyntaxHighlighting();
      this.registerTikzCodeBlock();
      if (this.settings.inlineLivePreviewEnabledByDefault) {
        this.inlinePreview.enable(500);
      }
    });
  }
  onunload() {
    this.removeSyntaxHighlighting();
    this.inlinePreview.disable();
    this.inlinePreview.clearTimer();
    this.renderer.clearCache();
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
      this.renderer.clearCache();
    });
  }
  registerTikzCodeBlock() {
    this.registerMarkdownCodeBlockProcessor("tikz", (source, el) => __async(this, null, function* () {
      el.empty();
      el.createDiv({ cls: "tikzjax-hebrew-local-output", text: "Rendering\u2026" });
      const render = () => __async(this, null, function* () {
        var _a;
        try {
          const cleaned = tidyTikzSource(source);
          if (!cleaned.trim()) {
            showTikzError(el, "Nothing to render.");
            return;
          }
          const result = yield this.renderer.renderToSvg(cleaned);
          if (!result.ok || !result.dataUrl || !result.svgText) {
            const retry = result.timedOut ? () => {
              el.empty();
              el.createDiv({ cls: "tikzjax-hebrew-local-output", text: "Rendering\u2026" });
              void render();
            } : void 0;
            showTikzError(el, (_a = result.error) != null ? _a : "Render failed.", result.rawLog, retry);
            return;
          }
          renderTikzDiagram(el, result);
        } catch (err) {
          showTikzError(el, "Render failed.", formatExecError(err));
        }
      });
      yield render();
    }));
  }
  toggleInlineLivePreview() {
    if (this.inlinePreview.enabled) {
      this.inlinePreview.disable();
      new import_obsidian3.Notice("Live preview off.");
      return;
    }
    this.inlinePreview.enable(0);
    new import_obsidian3.Notice("Live preview on.");
  }
  addSyntaxHighlighting() {
    window.CodeMirror.modeInfo.push({ name: "Tikz", mime: "text/x-latex", mode: "stex" });
  }
  removeSyntaxHighlighting() {
    window.CodeMirror.modeInfo = window.CodeMirror.modeInfo.filter((el) => el.name != "Tikz");
  }
};
