/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
__export(exports, {
  default: () => TikzjaxHebrewLocalPlugin
});
var import_obsidian2 = __toModule(require("obsidian"));
var import_child_process = __toModule(require("child_process"));
var import_util = __toModule(require("util"));

// latexAutocomplete.ts
var import_autocomplete = __toModule(require("@codemirror/autocomplete"));
var latexCommands = [
  (0, import_autocomplete.snippetCompletion)(String.raw`\begin\{tikzpicture\}
\${}
\end\{tikzpicture\}`, {
    label: "\\begin{tikzpicture}",
    type: "keyword",
    detail: "TikZ environment"
  }),
  {
    label: "\\end{tikzpicture}",
    type: "keyword",
    apply: "\\end{tikzpicture}",
    detail: "End TikZ environment"
  },
  (0, import_autocomplete.snippetCompletion)(String.raw`\begin\{axis\}
\${}
\end\{axis\}`, {
    label: "\\begin{axis}",
    type: "keyword",
    detail: "Pgfplots axis environment"
  }),
  {
    label: "\\end{axis}",
    type: "keyword",
    apply: "\\end{axis}",
    detail: "End axis environment"
  },
  {
    label: "\\draw",
    type: "function",
    apply: "\\draw ",
    detail: "TikZ draw command"
  },
  {
    label: "\\fill",
    type: "function",
    apply: "\\fill ",
    detail: "Fill a path"
  },
  {
    label: "\\filldraw",
    type: "function",
    apply: "\\filldraw ",
    detail: "Fill and stroke a path"
  },
  {
    label: "\\path",
    type: "function",
    apply: "\\path ",
    detail: "TikZ path without drawing"
  },
  {
    label: "\\node",
    type: "function",
    apply: "\\node ",
    detail: "TikZ node command"
  },
  {
    label: "\\coordinate",
    type: "function",
    apply: "\\coordinate ",
    detail: "Named coordinate"
  },
  {
    label: "\\clip",
    type: "function",
    apply: "\\clip ",
    detail: "Clip to a path"
  },
  (0, import_autocomplete.snippetCompletion)(String.raw`\foreach \x in \{1,...,5\} \{
  \${}
\}`, {
    label: "\\foreach",
    type: "function",
    detail: "Loop over values"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\scope
\${}
\endscope`, {
    label: "\\scope",
    type: "function",
    detail: "Local TikZ scope"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\tikzset\{\${}\}`, {
    label: "\\tikzset",
    type: "function",
    detail: "Set TikZ styles"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\usetikzlibrary\{\${}\}`, {
    label: "\\usetikzlibrary",
    type: "function",
    detail: "Load TikZ library"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\he\{\${}\}`, {
    label: "\\he{}",
    type: "function",
    detail: "Hebrew text wrapper"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\text\{\${}\}`, {
    label: "\\text{}",
    type: "function",
    detail: "Text in math mode"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\frac\{\${1}\}\{\${2}\}`, {
    label: "\\frac{}{}",
    type: "function",
    detail: "Fraction"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\cfrac\{\${1}\}\{\${2}\}`, {
    label: "\\cfrac{}{}",
    type: "function",
    detail: "Display fraction"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\sqrt\{\${}\}`, {
    label: "\\sqrt{}",
    type: "function",
    detail: "Square root"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\sum_\{\${1}\}\^\{\${2}\}`, {
    label: "\\sum_{}^{}",
    type: "function",
    detail: "Summation"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\int_\{\${1}\}\^\{\${2}\}`, {
    label: "\\int_{}^{}",
    type: "function",
    detail: "Integral"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\lim_\{\${}\}`, {
    label: "\\lim_{}",
    type: "function",
    detail: "Limit"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\vec\{\${}\}`, {
    label: "\\vec{}",
    type: "function",
    detail: "Vector arrow"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\hat\{\${}\}`, {
    label: "\\hat{}",
    type: "function",
    detail: "Hat accent"
  }),
  (0, import_autocomplete.snippetCompletion)(String.raw`\bar\{\${}\}`, {
    label: "\\bar{}",
    type: "function",
    detail: "Bar accent"
  }),
  {
    label: "\\alpha",
    type: "variable",
    apply: "\\alpha",
    detail: "Greek letter"
  },
  {
    label: "\\beta",
    type: "variable",
    apply: "\\beta",
    detail: "Greek letter"
  },
  {
    label: "\\gamma",
    type: "variable",
    apply: "\\gamma",
    detail: "Greek letter"
  },
  {
    label: "\\delta",
    type: "variable",
    apply: "\\delta",
    detail: "Greek letter"
  },
  {
    label: "\\Delta",
    type: "variable",
    apply: "\\Delta",
    detail: "Greek letter"
  },
  {
    label: "\\theta",
    type: "variable",
    apply: "\\theta",
    detail: "Greek letter"
  },
  {
    label: "\\lambda",
    type: "variable",
    apply: "\\lambda",
    detail: "Greek letter"
  },
  {
    label: "\\mu",
    type: "variable",
    apply: "\\mu",
    detail: "Greek letter"
  },
  {
    label: "\\pi",
    type: "variable",
    apply: "\\pi",
    detail: "Greek letter"
  },
  {
    label: "\\sigma",
    type: "variable",
    apply: "\\sigma",
    detail: "Greek letter"
  },
  {
    label: "\\omega",
    type: "variable",
    apply: "\\omega",
    detail: "Greek letter"
  },
  {
    label: "\\Omega",
    type: "variable",
    apply: "\\Omega",
    detail: "Greek letter"
  },
  {
    label: "\\infty",
    type: "variable",
    apply: "\\infty",
    detail: "Infinity symbol"
  },
  {
    label: "\\partial",
    type: "variable",
    apply: "\\partial",
    detail: "Partial derivative"
  },
  {
    label: "\\nabla",
    type: "variable",
    apply: "\\nabla",
    detail: "Nabla operator"
  },
  {
    label: "\\cdot",
    type: "variable",
    apply: "\\cdot",
    detail: "Multiplication dot"
  },
  {
    label: "\\times",
    type: "variable",
    apply: "\\times",
    detail: "Multiplication cross"
  },
  {
    label: "\\pm",
    type: "variable",
    apply: "\\pm",
    detail: "Plus/minus"
  },
  {
    label: "\\leq",
    type: "variable",
    apply: "\\leq",
    detail: "Less than or equal"
  },
  {
    label: "\\geq",
    type: "variable",
    apply: "\\geq",
    detail: "Greater than or equal"
  },
  {
    label: "\\neq",
    type: "variable",
    apply: "\\neq",
    detail: "Not equal"
  },
  {
    label: "\\approx",
    type: "variable",
    apply: "\\approx",
    detail: "Approximately equal"
  }
];
var simpleShapeHelpers = [
  { label: "\\Circle(,,)", apply: "\\Circle(0,0,1)", detail: "Circle outline" },
  { label: "\\FilledCircle(,,)", apply: "\\FilledCircle(0,0,1)", detail: "Filled circle" },
  { label: "\\Point(,)", apply: "\\Point(0,0)", detail: "Small point" },
  { label: "\\Line(,,,)", apply: "\\Line(0,0,1,1)", detail: "Line segment" },
  { label: "\\Arrow(,,,)", apply: "\\Arrow(0,0,1,1)", detail: "Arrow" },
  { label: "\\DArrow(,,,)", apply: "\\DArrow(0,0,1,1)", detail: "Double arrow" },
  { label: "\\DashedLine(,,,)", apply: "\\DashedLine(0,0,1,1)", detail: "Dashed line" },
  { label: "\\DottedLine(,,,)", apply: "\\DottedLine(0,0,1,1)", detail: "Dotted line" },
  { label: "\\HLine(,,)", apply: "\\HLine(0,1,0)", detail: "Horizontal line" },
  { label: "\\VLine(,,)", apply: "\\VLine(0,1,0)", detail: "Vertical line" },
  { label: "\\Rect(,,,)", apply: "\\Rect(0,0,1,1)", detail: "Rectangle outline" },
  { label: "\\FilledRect(,,,)", apply: "\\FilledRect(0,0,1,1)", detail: "Filled rectangle" },
  { label: "\\RoundedRect(,,,)", apply: "\\RoundedRect(0,0,1,1)", detail: "Rounded rectangle" },
  { label: "\\FilledRoundedRect(,,,)", apply: "\\FilledRoundedRect(0,0,1,1)", detail: "Filled rounded rectangle" },
  { label: "\\Ellipse(,,,)", apply: "\\Ellipse(0,0,1,0.5)", detail: "Ellipse outline" },
  { label: "\\FilledEllipse(,,,)", apply: "\\FilledEllipse(0,0,1,0.5)", detail: "Filled ellipse" },
  { label: "\\Cross(,,)", apply: "\\Cross(0,0,0.2)", detail: "Cross marker" },
  { label: "\\Diamond(,,,)", apply: "\\Diamond(0,0,0.5,0.3)", detail: "Diamond outline" },
  { label: "\\FilledDiamond(,,,)", apply: "\\FilledDiamond(0,0,0.5,0.3)", detail: "Filled diamond" },
  { label: "\\Arc(,,,,)", apply: "\\Arc(0,0,1,0,90)", detail: "Circular arc" },
  { label: "\\RightAngle(,,)", apply: "\\RightAngle(0,0,0.2)", detail: "Right-angle mark" },
  { label: "\\Grid(,,,,)", apply: "\\Grid(0,0,3,3,0.5)", detail: "Grid" },
  { label: "\\Triangle(,,,,,)", apply: "\\Triangle(0,0,1,0,0.5,1)", detail: "Triangle outline" },
  { label: "\\FilledTriangle(,,,,,)", apply: "\\FilledTriangle(0,0,1,0,0.5,1)", detail: "Filled triangle" },
  { label: "\\Axis(,,,)", apply: "\\Axis(-1,3,-1,3)", detail: "XY axes with labels" },
  { label: "\\AxisNamed(,,,,,)", apply: "\\AxisNamed(-1,3,-1,3,x,y)", detail: "Named axes" },
  { label: "\\Text(,,)", apply: "\\Text(0,0,text)", detail: "Text node" },
  { label: "\\SmallText(,,)", apply: "\\SmallText(0,0,text)", detail: "Small text node" },
  { label: "\\TinyText(,,)", apply: "\\TinyText(0,0,text)", detail: "Tiny text node" },
  { label: "\\TextAbove(,,)", apply: "\\TextAbove(0,0,text)", detail: "Text above point" },
  { label: "\\TextBelow(,,)", apply: "\\TextBelow(0,0,text)", detail: "Text below point" },
  { label: "\\TextLeft(,,)", apply: "\\TextLeft(0,0,text)", detail: "Text left of point" },
  { label: "\\TextRight(,,)", apply: "\\TextRight(0,0,text)", detail: "Text right of point" },
  { label: "\\Resistor(,,,)", apply: "\\Resistor(0,0,1,0.3)", detail: "Resistor symbol" },
  { label: "\\Capacitor(,,,)", apply: "\\Capacitor(0,0,0.4,0.3)", detail: "Capacitor symbol" },
  { label: "\\Ground(,,)", apply: "\\Ground(0,0,0.5)", detail: "Ground symbol" },
  { label: "\\VSource(,,,)", apply: "\\VSource(0,0,0.3,V)", detail: "Voltage source" },
  { label: "\\ANDgate(,,)", apply: "\\ANDgate(0,0,and1)", detail: "AND gate" },
  { label: "\\ORgate(,,)", apply: "\\ORgate(0,0,or1)", detail: "OR gate" },
  { label: "\\NOTgate(,,)", apply: "\\NOTgate(0,0,not1)", detail: "NOT gate" },
  { label: "\\NANDgate(,,)", apply: "\\NANDgate(0,0,nand1)", detail: "NAND gate" },
  { label: "\\NORgate(,,)", apply: "\\NORgate(0,0,nor1)", detail: "NOR gate" },
  { label: "\\XORgate(,,)", apply: "\\XORgate(0,0,xor1)", detail: "XOR gate" },
  { label: "\\XNORgate(,,)", apply: "\\XNORgate(0,0,xnor1)", detail: "XNOR gate" },
  { label: "\\BUFFERgate(,,)", apply: "\\BUFFERgate(0,0,buffer1)", detail: "Buffer gate" },
  { label: "\\LogicWire(,)", apply: "\\LogicWire(a,b)", detail: "Orthogonal wire" },
  { label: "\\LogicWireArrow(,)", apply: "\\LogicWireArrow(a,b)", detail: "Wire with arrow" },
  { label: "\\LogicWireDirect(,)", apply: "\\LogicWireDirect(a,b)", detail: "Direct wire" },
  { label: "\\LogicWireFrom(,,)", apply: "\\LogicWireFrom(0,0,a)", detail: "Wire from coordinate" },
  { label: "\\LogicWireFromArrow(,,)", apply: "\\LogicWireFromArrow(0,0,a)", detail: "Arrow wire from coordinate" },
  { label: "\\LogicWireTo(,,)", apply: "\\LogicWireTo(a,0,0)", detail: "Wire to coordinate" },
  { label: "\\LogicWireToArrow(,,)", apply: "\\LogicWireToArrow(a,0,0)", detail: "Arrow wire to coordinate" }
];
var tikzOptions = [
  { label: "->", type: "property", apply: "->", detail: "Arrow tip" },
  { label: "<-", type: "property", apply: "<-", detail: "Reverse arrow tip" },
  { label: "<->", type: "property", apply: "<->", detail: "Double arrow" },
  { label: "-Stealth", type: "property", apply: "-Stealth", detail: "Stealth arrow" },
  { label: "Stealth-Stealth", type: "property", apply: "Stealth-Stealth", detail: "Stealth both ends" },
  { label: "thick", type: "property", apply: "thick", detail: "Thick line" },
  { label: "very thick", type: "property", apply: "very thick", detail: "Very thick line" },
  { label: "thin", type: "property", apply: "thin", detail: "Thin line" },
  { label: "dashed", type: "property", apply: "dashed", detail: "Dashed line" },
  { label: "dotted", type: "property", apply: "dotted", detail: "Dotted line" },
  { label: "line width=1pt", type: "property", apply: "line width=1pt", detail: "Line width" },
  { label: "rounded corners", type: "property", apply: "rounded corners", detail: "Rounded corners" },
  { label: "circle", type: "property", apply: "circle", detail: "Circle shape" },
  { label: "rectangle", type: "property", apply: "rectangle", detail: "Rectangle shape" },
  { label: "ellipse", type: "property", apply: "ellipse", detail: "Ellipse shape" },
  { label: "draw=black", type: "property", apply: "draw=black", detail: "Stroke color" },
  { label: "fill=cyan!10", type: "property", apply: "fill=cyan!10", detail: "Fill color" },
  { label: "fill=blue!20", type: "property", apply: "fill=blue!20", detail: "Light blue fill" },
  { label: "fill=red!20", type: "property", apply: "fill=red!20", detail: "Light red fill" },
  { label: "fill=green!20", type: "property", apply: "fill=green!20", detail: "Light green fill" },
  { label: "fill=none", type: "property", apply: "fill=none", detail: "No fill" },
  { label: "opacity=0.5", type: "property", apply: "opacity=0.5", detail: "Opacity" },
  { label: "font=\\small", type: "property", apply: "font=\\small", detail: "Small font" },
  { label: "font=\\tiny", type: "property", apply: "font=\\tiny", detail: "Tiny font" },
  { label: "align=center", type: "property", apply: "align=center", detail: "Centered text" },
  { label: "align=left", type: "property", apply: "align=left", detail: "Left-aligned text" },
  { label: "align=right", type: "property", apply: "align=right", detail: "Right-aligned text" },
  { label: "anchor=north", type: "property", apply: "anchor=north", detail: "North anchor" },
  { label: "anchor=south", type: "property", apply: "anchor=south", detail: "South anchor" },
  { label: "anchor=east", type: "property", apply: "anchor=east", detail: "East anchor" },
  { label: "anchor=west", type: "property", apply: "anchor=west", detail: "West anchor" },
  { label: "inner sep=2pt", type: "property", apply: "inner sep=2pt", detail: "Inner padding" },
  { label: "outer sep=0pt", type: "property", apply: "outer sep=0pt", detail: "Outer padding" },
  { label: "minimum width=1cm", type: "property", apply: "minimum width=1cm", detail: "Minimum width" },
  { label: "minimum height=1cm", type: "property", apply: "minimum height=1cm", detail: "Minimum height" },
  { label: "scale=0.8", type: "property", apply: "scale=0.8", detail: "Scale factor" },
  { label: "rotate=45", type: "property", apply: "rotate=45", detail: "Rotation" },
  { label: "xshift=1cm", type: "property", apply: "xshift=1cm", detail: "Horizontal shift" },
  { label: "yshift=1cm", type: "property", apply: "yshift=1cm", detail: "Vertical shift" },
  { label: "below=of", type: "property", apply: "below=of ", detail: "Position below node" },
  { label: "right=of", type: "property", apply: "right=of ", detail: "Position right of node" },
  { label: "above=of", type: "property", apply: "above=of ", detail: "Position above node" },
  { label: "left=of", type: "property", apply: "left=of ", detail: "Position left of node" }
];
var tikzLibraries = [
  { label: "arrows.meta", type: "text", apply: "arrows.meta", detail: "Arrow tips" },
  { label: "positioning", type: "text", apply: "positioning", detail: "Relative positioning" },
  { label: "calc", type: "text", apply: "calc", detail: "Coordinate calculations" },
  { label: "shapes", type: "text", apply: "shapes", detail: "Extra shapes" },
  { label: "decorations.pathmorphing", type: "text", apply: "decorations.pathmorphing", detail: "Path decorations" },
  { label: "shapes.gates.logic.US", type: "text", apply: "shapes.gates.logic.US", detail: "Logic gates" },
  { label: "matrix", type: "text", apply: "matrix", detail: "Matrix layouts" },
  { label: "fit", type: "text", apply: "fit", detail: "Fit nodes around content" },
  { label: "backgrounds", type: "text", apply: "backgrounds", detail: "Background layers" }
];
var allCommandCompletions = [...latexCommands, ...simpleShapeHelpers];
function insideLatexOrTikzBlock(textBeforeCursor) {
  const fencePattern = /```(?:tikz|latex|lualatex|tex)\b/g;
  let lastOpen = -1;
  let match;
  while ((match = fencePattern.exec(textBeforeCursor)) !== null) {
    lastOpen = match.index;
  }
  if (lastOpen === -1) {
    return false;
  }
  const afterOpen = textBeforeCursor.slice(lastOpen);
  const lines = afterOpen.split("\n");
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === "```") {
      return false;
    }
  }
  return true;
}
function filterCompletions(options, prefix) {
  const lowerPrefix = prefix.toLowerCase();
  return options.filter((option) => option.label.toLowerCase().startsWith(lowerPrefix));
}
function latexCompletionSource(context) {
  const textBeforeCursor = context.state.doc.sliceString(0, context.pos);
  if (!insideLatexOrTikzBlock(textBeforeCursor)) {
    return null;
  }
  const commandMatch = context.matchBefore(/\\(?:[A-Za-z]+|\{)?/);
  if (commandMatch) {
    const prefix = commandMatch.text;
    return {
      from: commandMatch.from,
      options: filterCompletions(allCommandCompletions, prefix),
      validFor: /^\\(?:[A-Za-z]+|\{)?$/
    };
  }
  const libraryMatch = context.matchBefore(/\\usetikzlibrary\{[^}]*\}?/);
  if (libraryMatch) {
    const openBrace = libraryMatch.text.indexOf("{");
    if (openBrace !== -1) {
      const prefix = libraryMatch.text.slice(openBrace + 1).replace(/}$/, "");
      const from = libraryMatch.from + openBrace + 1;
      return {
        from,
        options: filterCompletions(tikzLibraries, prefix),
        validFor: /^[^}]*$/
      };
    }
  }
  const bracketOptionMatch = context.matchBefore(/(?:^|[\[\s,{])([A-Za-z!\\=0-9.<>\-]+)?/);
  if (bracketOptionMatch) {
    const prefix = bracketOptionMatch.text.replace(/^[\[\s,{]+/, "");
    const charBefore = context.state.doc.sliceString(Math.max(0, context.pos - 1), context.pos);
    if (prefix.length > 0 || charBefore === "[" || charBefore === "," || context.explicit) {
      return {
        from: context.pos - prefix.length,
        options: filterCompletions(tikzOptions, prefix),
        validFor: /^[A-Za-z!\\=0-9.<>\-]*$/
      };
    }
  }
  return null;
}
function latexAutocompleteExtension() {
  return (0, import_autocomplete.autocompletion)({
    override: [latexCompletionSource],
    activateOnTyping: true,
    maxRenderedOptions: 40
  });
}

// latexErrorMapping.ts
var LATEX_LINE_PATTERN = /(?:^|\n)\s*l\.(\d+)/;
function getUserSourceLineOffset(wrapperPrefix) {
  if (!wrapperPrefix) {
    return 0;
  }
  return wrapperPrefix.split("\n").length;
}
function parseLatexErrorLine(raw) {
  const match = raw.match(LATEX_LINE_PATTERN);
  if (!match) {
    return null;
  }
  const line = parseInt(match[1], 10);
  return Number.isFinite(line) ? line : null;
}
function extractUsefulLatexError(raw) {
  const lines = raw.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  const bangLine = lines.find((line) => line.startsWith("! "));
  if (bangLine) {
    return bangLine.replace(/^!\s*/, "").trim();
  }
  const usefulLine = lines.find((line) => line.includes("Undefined control sequence") || line.includes("Missing") || line.includes("Runaway argument") || line.includes("Fatal error"));
  if (usefulLine) {
    return usefulLine.trim();
  }
  return "Syntax error";
}
function mapTidiedLineToNoteLine(blockStartLine, blockEndLine, getLineText, tidiedLine) {
  let nonEmptyIndex = 0;
  for (let line = blockStartLine + 1; line < blockEndLine; line++) {
    const text = getLineText(line).trim();
    if (!text) {
      continue;
    }
    nonEmptyIndex++;
    if (nonEmptyIndex === tidiedLine) {
      return line + 1;
    }
  }
  return null;
}
function formatLatexErrorWithLineMapping(raw, tidiedSource, sourceLineOffset, noteLineMapper) {
  var _a, _b;
  const usefulError = extractUsefulLatexError(raw);
  const latexLine = parseLatexErrorLine(raw);
  if (latexLine === null || latexLine <= sourceLineOffset) {
    return { message: usefulError };
  }
  const userLine = latexLine - sourceLineOffset;
  const sourceLines = tidiedSource.split("\n");
  const lineContent = (_a = sourceLines[userLine - 1]) == null ? void 0 : _a.trim();
  const noteLine = (_b = noteLineMapper == null ? void 0 : noteLineMapper(userLine)) != null ? _b : void 0;
  const snippet = lineContent ? lineContent.length > 80 ? `${lineContent.slice(0, 77)}...` : lineContent : usefulError;
  if (noteLine !== void 0) {
    return {
      message: `Error near line ${noteLine} in note (TikZ block line ${userLine}): ${snippet}`,
      userLine,
      lineContent,
      noteLine
    };
  }
  return {
    message: `Error near line ${userLine} in your TikZ block: ${snippet}`,
    userLine,
    lineContent
  };
}

// simpleShapes.ts
var SIMPLE_TIKZ_HELPERS = String.raw`
% ---------- Logic gates inherit scope / tikzpicture scaling ----------
\tikzset{
  every and gate US/.append style={transform shape},
  every or gate US/.append style={transform shape},
  every not gate US/.append style={transform shape},
  every nand gate US/.append style={transform shape},
  every nor gate US/.append style={transform shape},
  every xor gate US/.append style={transform shape},
  every xnor gate US/.append style={transform shape},
  every buffer gate US/.append style={transform shape},
}

% ---------- Simple drawing helpers ----------
\def\Circle(#1,#2,#3){\draw (#1,#2) circle (#3);}
\def\FilledCircle(#1,#2,#3){\fill (#1,#2) circle (#3);}
\def\Point(#1,#2){\fill (#1,#2) circle (1.7pt);}
\def\Line(#1,#2,#3,#4){\draw (#1,#2) -- (#3,#4);}
\def\Arrow(#1,#2,#3,#4){\draw[->] (#1,#2) -- (#3,#4);}
\def\DArrow(#1,#2,#3,#4){\draw[<->] (#1,#2) -- (#3,#4);}
\def\DashedLine(#1,#2,#3,#4){\draw[dashed] (#1,#2) -- (#3,#4);}
\def\DottedLine(#1,#2,#3,#4){\draw[dotted] (#1,#2) -- (#3,#4);}
\def\HLine(#1,#2,#3){\draw (#1,#3) -- (#2,#3);}
\def\VLine(#1,#2,#3){\draw (#3,#1) -- (#3,#2);}
\def\Rect(#1,#2,#3,#4){\draw (#1,#2) rectangle (#3,#4);}
\def\FilledRect(#1,#2,#3,#4){\fill (#1,#2) rectangle (#3,#4);}
\def\RoundedRect(#1,#2,#3,#4){\draw[rounded corners] (#1,#2) rectangle (#3,#4);}
\def\FilledRoundedRect(#1,#2,#3,#4){\fill[rounded corners] (#1,#2) rectangle (#3,#4);}
\def\Ellipse(#1,#2,#3,#4){\draw (#1,#2) ellipse (#3 and #4);}
\def\FilledEllipse(#1,#2,#3,#4){\fill (#1,#2) ellipse (#3 and #4);}
\def\Cross(#1,#2,#3){
\draw (#1-#3,#2) -- (#1+#3,#2);
\draw (#1,#2-#3) -- (#1,#2+#3);
}
\def\Diamond(#1,#2,#3,#4){
\draw (#1,#2+#4) -- (#1+#3,#2) -- (#1,#2-#4) -- (#1-#3,#2) -- cycle;
}
\def\FilledDiamond(#1,#2,#3,#4){
\fill (#1,#2+#4) -- (#1+#3,#2) -- (#1,#2-#4) -- (#1-#3,#2) -- cycle;
}
\def\Arc(#1,#2,#3,#4,#5){\draw (#1,#2) arc (#4:#5:#3);}
\def\RightAngle(#1,#2,#3){
\draw (#1,#2+#3) -- (#1,#2) -- (#1+#3,#2);
}
\def\Grid(#1,#2,#3,#4,#5){
\draw[step=#5] (#1,#2) grid (#3,#4);
}
\def\Axis(#1,#2,#3,#4){
\draw[->] (#1,0) -- (#2,0) node[right] {$x$};
\draw[->] (0,#3) -- (0,#4) node[above] {$y$};
}
\def\AxisNamed(#1,#2,#3,#4,#5,#6){
\draw[->] (#1,0) -- (#2,0) node[right] {#5};
\draw[->] (0,#3) -- (0,#4) node[above] {#6};
}

% ---------- Simple text helpers ----------
\def\Text(#1,#2,#3){\node[transform shape] at (#1,#2) {#3};}
\def\SmallText(#1,#2,#3){\node[font=\small, transform shape] at (#1,#2) {#3};}
\def\TinyText(#1,#2,#3){\node[font=\tiny, transform shape] at (#1,#2) {#3};}
\def\TextAbove(#1,#2,#3){\node[above, transform shape] at (#1,#2) {#3};}
\def\TextBelow(#1,#2,#3){\node[below, transform shape] at (#1,#2) {#3};}
\def\TextLeft(#1,#2,#3){\node[left, transform shape] at (#1,#2) {#3};}
\def\TextRight(#1,#2,#3){\node[right, transform shape] at (#1,#2) {#3};}

% ---------- Simple logic gates ----------
\def\ANDgate(#1,#2,#3){
\node[and gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\ORgate(#1,#2,#3){
\node[or gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\NOTgate(#1,#2,#3){
\node[not gate US, draw, anchor=input, transform shape] (#3) at (#1,#2) {};
}

% ---------- More logic gates ----------
\def\BUFFERgate(#1,#2,#3){
\node[buffer gate US, draw, anchor=input, transform shape] (#3) at (#1,#2) {};
}

\def\NANDgate(#1,#2,#3){
\node[nand gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\NORgate(#1,#2,#3){
\node[nor gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\XORgate(#1,#2,#3){
\node[xor gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

\def\XNORgate(#1,#2,#3){
\node[xnor gate US, draw, logic gate inputs=nn, anchor=input 1, transform shape] (#3) at (#1,#2) {};
}

% ---------- Logic-gate wire helpers ----------
\def\LogicWire(#1,#2){
\draw (#1) -- ++(0.35,0) |- (#2);
}

\def\LogicWireArrow(#1,#2){
\draw[->] (#1) -- ++(0.35,0) |- (#2);
}

\def\LogicWireDirect(#1,#2){
\draw (#1) -- (#2);
}

\def\LogicWireFrom(#1,#2,#3){
\draw (#1,#2) -- ++(0.35,0) |- (#3);
}

\def\LogicWireFromArrow(#1,#2,#3){
\draw[->] (#1,#2) -- ++(0.35,0) |- (#3);
}

\def\LogicWireTo(#1,#2,#3){
\draw (#1) -- ++(0.35,0) |- (#2,#3);
}

\def\LogicWireToArrow(#1,#2,#3){
\draw[->] (#1) -- ++(0.35,0) |- (#2,#3);
}

\def\Triangle(#1,#2,#3,#4,#5,#6){
\draw (#1,#2) -- (#3,#4) -- (#5,#6) -- cycle;
}

\def\FilledTriangle(#1,#2,#3,#4,#5,#6){
\fill (#1,#2) -- (#3,#4) -- (#5,#6) -- cycle;
}

% ---------- Simple circuit symbols ----------
\def\Resistor(#1,#2,#3,#4){
\draw (#1,#2) -- ++(0.15,0);
\draw (#1+0.15,#2-#4/2) rectangle ++(#3-0.3,#4);
\draw (#1+#3-0.15,#2) -- ++(0.15,0);
}

\def\Capacitor(#1,#2,#3,#4){
\draw (#1,#2) -- ++(0.15,0);
\draw (#1+0.15,#2-#4) -- (#1+0.15,#2+#4);
\draw (#1+0.15+#3,#2-#4) -- (#1+0.15+#3,#2+#4);
\draw (#1+0.15+#3,#2) -- ++(0.15,0);
}

\def\Ground(#1,#2,#3){
\draw (#1,#2) -- (#1,#2-#3);
\draw (#1-0.25,#2-#3) -- (#1+0.25,#2-#3);
\draw (#1-0.15,#2-#3-0.12) -- (#1+0.15,#2-#3-0.12);
\draw (#1-0.08,#2-#3-0.24) -- (#1+0.08,#2-#3-0.24);
}

\def\VSource(#1,#2,#3,#4){
\draw (#1,#2) circle (#3);
\node[transform shape] at (#1,#2) {$#4$};
}
`;

// settings.ts
var import_obsidian = __toModule(require("obsidian"));
var TikzjaxSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Invert dark colors in dark mode").setDesc("Invert dark colors in diagrams (e.g. axes, arrows) when in dark mode, so that they are visible.").addToggle((toggle) => toggle.setValue(this.plugin.settings.invertColorsInDarkMode).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.invertColorsInDarkMode = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian.Setting(containerEl).setName("Enable inline live preview by default").setDesc("Automatically show the floating live TikZ preview when the cursor is inside a TikZ block.").addToggle((toggle) => toggle.setValue(this.plugin.settings.inlineLivePreviewEnabledByDefault).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.inlineLivePreviewEnabledByDefault = value;
      yield this.plugin.saveSettings();
    })));
  }
};

// main.ts
var fs = __toModule(require("fs"));
var path = __toModule(require("path"));
var os = __toModule(require("os"));
var DEFAULT_SETTINGS = {
  invertColorsInDarkMode: true,
  inlineLivePreviewEnabledByDefault: true
};
var execFileAsync = (0, import_util.promisify)(import_child_process.execFile);
var DOCUMENTCLASS_LINE = "\\documentclass[tikz,border=5pt]{standalone}\n";
var LATEX_WRAPPER_PREFIX = `${DOCUMENTCLASS_LINE}\\usepackage{fontspec}
\\usepackage{polyglossia}

\\setmainlanguage{english}
\\setotherlanguage{hebrew}

\\newfontfamily\\hebrewfont[Script=Hebrew]{David CLM}
\\newfontfamily\\hebrewfontsf[Script=Hebrew]{David CLM}
\\newfontfamily\\hebrewfonttt[Script=Hebrew]{David CLM}

\\usepackage{tikz}
\\usetikzlibrary{arrows.meta,positioning,calc,shapes,decorations.pathmorphing,shapes.gates.logic.US}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{circuitikz}
\\usepackage{pgfplots}
\\pgfplotsset{compat=1.18}

\\newcommand{\\he}[1]{\\texthebrew{#1}}
${SIMPLE_TIKZ_HELPERS}
\\begin{document}
`;
var LATEX_WRAPPER_SUFFIX = `
\\end{document}
`;
var USER_SOURCE_LINE_OFFSET = getUserSourceLineOffset(LATEX_WRAPPER_PREFIX);
function fileExists(filePath) {
  return __async(this, null, function* () {
    return fs.existsSync(filePath);
  });
}
function resolveCommand(commandName, candidates) {
  return __async(this, null, function* () {
    for (const candidate of candidates) {
      if (candidate.includes("/")) {
        if (yield fileExists(candidate)) {
          return candidate;
        }
        continue;
      }
      try {
        const { stdout } = yield execFileAsync("/usr/bin/which", [candidate]);
        const resolved = stdout.trim();
        if (resolved) {
          return resolved;
        }
      } catch (e) {
      }
    }
    return null;
  });
}
function resolveLuaLatex() {
  return __async(this, null, function* () {
    return resolveCommand("lualatex", [
      "/Library/TeX/texbin/lualatex",
      "/usr/local/texlive/2025/bin/universal-darwin/lualatex",
      "/usr/local/bin/lualatex",
      "lualatex"
    ]);
  });
}
function resolvePdfToCairo() {
  return __async(this, null, function* () {
    return resolveCommand("pdftocairo", [
      "/opt/homebrew/bin/pdftocairo",
      "/usr/local/bin/pdftocairo",
      "/usr/bin/pdftocairo",
      "pdftocairo"
    ]);
  });
}
function wrapLatexSource(source) {
  let cleanedSource = source;
  cleanedSource = cleanedSource.replace(/\\documentclass(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\usepackage(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\pgfplotsset\{[^}]*\}/g, "");
  cleanedSource = cleanedSource.replace(/\\begin\{document\}/g, "");
  cleanedSource = cleanedSource.replace(/\\end\{document\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setmainlanguage\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setotherlanguage\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setmainfont(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setsansfont(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\newfontfamily\\\w+(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  return LATEX_WRAPPER_PREFIX + cleanedSource.trim() + LATEX_WRAPPER_SUFFIX;
}
function readLogTail(logPath, maxChars = 8e3) {
  if (!fs.existsSync(logPath)) {
    return "";
  }
  const log = fs.readFileSync(logPath, "utf8");
  if (log.length <= maxChars) {
    return log;
  }
  return "...(truncated)...\n" + log.slice(-maxChars);
}
function formatExecError(err) {
  if (err instanceof Error) {
    const execErr = err;
    const parts = [execErr.message];
    if (execErr.stdout) {
      parts.push(execErr.stdout);
    }
    if (execErr.stderr) {
      parts.push(execErr.stderr);
    }
    return parts.join("\n");
  }
  return String(err);
}
function getCurrentTikzBlock(editor) {
  const cursor = editor.getCursor();
  const lineCount = editor.lineCount();
  let startLine = -1;
  for (let line = cursor.line; line >= 0; line--) {
    const text = editor.getLine(line).trim();
    if (text.startsWith("```tikz")) {
      startLine = line;
      break;
    }
    if (text === "```") {
      return null;
    }
  }
  if (startLine === -1) {
    return null;
  }
  let endLine = -1;
  for (let line = startLine + 1; line < lineCount; line++) {
    const text = editor.getLine(line).trim();
    if (text === "```") {
      endLine = line;
      break;
    }
  }
  if (endLine === -1) {
    return null;
  }
  if (cursor.line <= startLine || cursor.line >= endLine) {
    return null;
  }
  const source = editor.getRange({ line: startLine + 1, ch: 0 }, { line: endLine, ch: 0 });
  return {
    source,
    startLine,
    endLine
  };
}
var TikzjaxHebrewLocalPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.inlinePreviewEnabled = false;
    this.inlinePreviewContainer = null;
    this.inlinePreviewTimer = null;
    this.inlinePreviewLastGoodDataUrl = null;
    this.inlinePreviewLastSource = null;
    this.inlinePreviewRenderToken = 0;
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.registerEditorExtension(latexAutocompleteExtension());
      this.addCommand({
        id: "toggle-tikz-inline-live-preview",
        name: "LuaTikZ: Toggle inline live preview",
        callback: () => {
          this.toggleInlineLivePreview();
        }
      });
      this.registerEvent(this.app.workspace.on("editor-change", () => {
        this.scheduleInlinePreviewUpdate();
      }));
      this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
        this.scheduleInlinePreviewUpdate();
      }));
      this.registerDomEvent(document, "selectionchange", () => {
        this.scheduleInlinePreviewUpdate();
      });
      this.addSettingTab(new TikzjaxSettingTab(this.app, this));
      this.addSyntaxHighlighting();
      this.registerTikzCodeBlock();
      if (this.settings.inlineLivePreviewEnabledByDefault) {
        this.inlinePreviewEnabled = true;
        this.scheduleInlinePreviewUpdate(500);
      }
    });
  }
  onunload() {
    this.removeSyntaxHighlighting();
    this.disableInlineLivePreview();
    if (this.inlinePreviewTimer) {
      window.clearTimeout(this.inlinePreviewTimer);
    }
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  registerTikzCodeBlock() {
    this.registerMarkdownCodeBlockProcessor("tikz", (source, el) => __async(this, null, function* () {
      el.empty();
      const loadingEl = el.createDiv({ cls: "tikzjax-hebrew-local-output" });
      loadingEl.setText("Rendering TikZ diagram\u2026");
      try {
        const cleanedSource = this.tidyTikzSource(source);
        if (!cleanedSource.trim()) {
          this.showError(el, "Nothing to render.");
          return;
        }
        yield this.renderTikz(cleanedSource, el);
      } catch (err) {
        this.showError(el, "Render error.", formatExecError(err));
      }
    }));
  }
  toggleInlineLivePreview() {
    if (this.inlinePreviewEnabled) {
      this.disableInlineLivePreview();
      new import_obsidian2.Notice("LuaTikZ inline live preview disabled.");
      return;
    }
    this.inlinePreviewEnabled = true;
    new import_obsidian2.Notice("LuaTikZ inline live preview enabled.");
    this.scheduleInlinePreviewUpdate(0);
  }
  disableInlineLivePreview() {
    this.inlinePreviewEnabled = false;
    this.inlinePreviewLastGoodDataUrl = null;
    this.inlinePreviewLastSource = null;
    if (this.inlinePreviewTimer) {
      window.clearTimeout(this.inlinePreviewTimer);
      this.inlinePreviewTimer = null;
    }
    if (this.inlinePreviewContainer) {
      this.inlinePreviewContainer.remove();
      this.inlinePreviewContainer = null;
    }
  }
  scheduleInlinePreviewUpdate(delay = 800) {
    if (!this.inlinePreviewEnabled) {
      return;
    }
    if (this.inlinePreviewTimer) {
      window.clearTimeout(this.inlinePreviewTimer);
    }
    this.inlinePreviewTimer = window.setTimeout(() => {
      this.updateInlinePreviewFromActiveEditor();
    }, delay);
  }
  getActiveMarkdownView() {
    return this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
  }
  getOrCreateInlinePreviewContainer(markdownView) {
    if (this.inlinePreviewContainer && document.body.contains(this.inlinePreviewContainer)) {
      return this.inlinePreviewContainer;
    }
    const container = markdownView.containerEl.createDiv({
      cls: "tikzjax-hebrew-local-inline-preview"
    });
    this.inlinePreviewContainer = container;
    return container;
  }
  hideInlinePreview() {
    if (this.inlinePreviewContainer) {
      this.inlinePreviewContainer.remove();
      this.inlinePreviewContainer = null;
    }
  }
  showInlineMessage(markdownView, message) {
    const container = this.getOrCreateInlinePreviewContainer(markdownView);
    container.empty();
    container.createDiv({
      cls: "tikzjax-hebrew-local-inline-preview-message",
      text: message
    });
  }
  showInlineImage(markdownView, dataUrl) {
    const container = this.getOrCreateInlinePreviewContainer(markdownView);
    container.empty();
    const output = container.createDiv({
      cls: "tikzjax-hebrew-local-output"
    });
    const img = output.createEl("img");
    img.setAttr("src", dataUrl);
    img.setAttr("alt", "TikZ diagram");
    img.addClass("tikzjax-hebrew-local-image");
  }
  showInlineError(markdownView, message, details) {
    const container = this.getOrCreateInlinePreviewContainer(markdownView);
    const errorEl = container.createDiv({
      cls: "tikzjax-hebrew-local-error tikzjax-hebrew-local-inline-preview-error"
    });
    const titleEl = errorEl.createDiv({
      cls: "tikzjax-hebrew-local-error-title"
    });
    titleEl.setText(message);
    if (!details) {
      return;
    }
    const buttonRow = errorEl.createDiv({
      cls: "tikzjax-hebrew-local-error-button-row"
    });
    const copyButton = buttonRow.createEl("button", {
      text: "Copy error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    copyButton.addEventListener("click", () => __async(this, null, function* () {
      try {
        yield navigator.clipboard.writeText(details);
        new import_obsidian2.Notice("LuaTikZ error copied.");
      } catch (e) {
        new import_obsidian2.Notice("Could not copy error.");
      }
    }));
    const button = buttonRow.createEl("button", {
      text: "Show full error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    const detailsEl = errorEl.createEl("pre", {
      cls: "tikzjax-hebrew-local-error-details"
    });
    detailsEl.setText(details);
    detailsEl.style.display = "none";
    button.addEventListener("click", () => {
      const isHidden = detailsEl.style.display === "none";
      detailsEl.style.display = isHidden ? "block" : "none";
      button.setText(isHidden ? "Hide full error" : "Show full error");
    });
  }
  updateInlinePreviewFromActiveEditor() {
    return __async(this, null, function* () {
      var _a, _b;
      if (!this.inlinePreviewEnabled) {
        return;
      }
      const markdownView = this.getActiveMarkdownView();
      if (!markdownView) {
        this.hideInlinePreview();
        return;
      }
      const block = getCurrentTikzBlock(markdownView.editor);
      if (!block) {
        this.hideInlinePreview();
        return;
      }
      const cleanedSource = this.tidyTikzSource(block.source);
      if (!cleanedSource.trim()) {
        this.showInlineMessage(markdownView, "Nothing to render.");
        return;
      }
      if (cleanedSource === this.inlinePreviewLastSource && this.inlinePreviewLastGoodDataUrl) {
        return;
      }
      const token = ++this.inlinePreviewRenderToken;
      if (!this.inlinePreviewLastGoodDataUrl) {
        this.showInlineMessage(markdownView, "Rendering TikZ diagram\u2026");
      }
      const result = yield this.renderTikzToSvgDataUrl(cleanedSource, {
        block,
        editor: markdownView.editor
      });
      if (token !== this.inlinePreviewRenderToken) {
        return;
      }
      if (result.ok && result.dataUrl) {
        this.inlinePreviewLastSource = cleanedSource;
        this.inlinePreviewLastGoodDataUrl = result.dataUrl;
        this.showInlineImage(markdownView, result.dataUrl);
        return;
      }
      if (this.inlinePreviewLastGoodDataUrl) {
        this.showInlineImage(markdownView, this.inlinePreviewLastGoodDataUrl);
        this.showInlineError(markdownView, (_a = result.error) != null ? _a : "Render error.", result.rawLog);
        return;
      }
      const container = this.getOrCreateInlinePreviewContainer(markdownView);
      container.empty();
      this.showInlineError(markdownView, (_b = result.error) != null ? _b : "Render error.", result.rawLog);
    });
  }
  buildLatexErrorResult(rawError, tidiedSource, errorContext) {
    const noteLineMapper = (errorContext == null ? void 0 : errorContext.block) && errorContext.editor ? (userLine) => mapTidiedLineToNoteLine(errorContext.block.startLine, errorContext.block.endLine, (line) => errorContext.editor.getLine(line), userLine) : void 0;
    const mapped = formatLatexErrorWithLineMapping(rawError, tidiedSource, USER_SOURCE_LINE_OFFSET, noteLineMapper);
    return {
      ok: false,
      error: mapped.message,
      rawLog: rawError,
      userLine: mapped.userLine,
      noteLine: mapped.noteLine,
      lineContent: mapped.lineContent
    };
  }
  renderTikzToSvgDataUrl(source, errorContext) {
    return __async(this, null, function* () {
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "obsidian-tikz-hebrew-"));
      const texPath = path.join(tmpDir, "diagram.tex");
      const pdfPath = path.join(tmpDir, "diagram.pdf");
      const logPath = path.join(tmpDir, "diagram.log");
      const svgPath = path.join(tmpDir, "diagram.svg");
      const wrappedSource = wrapLatexSource(source);
      fs.writeFileSync(texPath, wrappedSource, "utf8");
      const lualatexPath = yield resolveLuaLatex();
      if (!lualatexPath) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "LuaLaTeX was not found.",
          rawLog: "On macOS, LuaLaTeX is usually located at:\n/Library/TeX/texbin/lualatex\n\nCheck in Terminal with:\nwhich lualatex"
        };
      }
      try {
        yield execFileAsync(lualatexPath, [
          "-interaction=nonstopmode",
          "-halt-on-error",
          `-output-directory=${tmpDir}`,
          texPath
        ], {
          cwd: tmpDir,
          maxBuffer: 10 * 1024 * 1024
        });
      } catch (err) {
        const logTail = readLogTail(logPath);
        const rawError = [
          formatExecError(err),
          logTail ? "\n--- diagram.log (tail) ---\n" + logTail : ""
        ].join("\n");
        const errorResult = this.buildLatexErrorResult(rawError, source, errorContext);
        this.cleanupTempDir(tmpDir);
        return errorResult;
      }
      if (!fs.existsSync(pdfPath)) {
        const logTail = readLogTail(logPath);
        const details = [
          "LuaLaTeX finished but diagram.pdf was not produced."
        ];
        if (logTail) {
          details.push("", "--- diagram.log (tail) ---", logTail);
          const errorResult = this.buildLatexErrorResult(details.join("\n"), source, errorContext);
          this.cleanupTempDir(tmpDir);
          return errorResult;
        }
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "LuaLaTeX finished, but no PDF was produced.",
          rawLog: details.join("\n")
        };
      }
      const pdftocairoPath = yield resolvePdfToCairo();
      if (!pdftocairoPath) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "PDF rendered, but SVG conversion is not available.",
          rawLog: `pdftocairo was not found.

Install it with:
brew install poppler

PDF path: ${pdfPath}`
        };
      }
      try {
        yield execFileAsync(pdftocairoPath, [
          "-svg",
          pdfPath,
          svgPath
        ], {
          cwd: tmpDir,
          maxBuffer: 30 * 1024 * 1024
        });
      } catch (err) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "PDF rendered, but SVG conversion failed.",
          rawLog: `PDF path: ${pdfPath}

${formatExecError(err)}`
        };
      }
      if (!fs.existsSync(svgPath)) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "PDF rendered, but no SVG was produced.",
          rawLog: `PDF path: ${pdfPath}`
        };
      }
      let svgText = fs.readFileSync(svgPath, "utf8");
      if (this.shouldConvertBlackToWhite()) {
        svgText = this.convertBlackSvgToWhite(svgText);
      }
      const svgBase64 = Buffer.from(svgText, "utf8").toString("base64");
      this.cleanupTempDir(tmpDir);
      return {
        ok: true,
        dataUrl: `data:image/svg+xml;base64,${svgBase64}`,
        svgText
      };
    });
  }
  downloadSvg(svgText, filename = "tikz-diagram.svg") {
    const blob = new Blob([svgText], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    link.style.display = "none";
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }
  createDiagramToolbar(parent, svgText) {
    const toolbar = parent.createDiv({ cls: "tikzjax-hebrew-local-toolbar" });
    const exportButton = toolbar.createEl("button", {
      text: "Export SVG",
      cls: "tikzjax-hebrew-local-toolbar-button"
    });
    exportButton.addEventListener("click", () => {
      this.downloadSvg(svgText);
      new import_obsidian2.Notice("TikZ diagram exported as SVG.");
    });
    const copyButton = toolbar.createEl("button", {
      text: "Copy SVG",
      cls: "tikzjax-hebrew-local-toolbar-button"
    });
    copyButton.addEventListener("click", () => __async(this, null, function* () {
      try {
        yield navigator.clipboard.writeText(svgText);
        new import_obsidian2.Notice("TikZ SVG copied to clipboard.");
      } catch (e) {
        new import_obsidian2.Notice("Could not copy SVG.");
      }
    }));
  }
  cleanupTempDir(tmpDir) {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch (e) {
    }
  }
  shouldConvertBlackToWhite() {
    return this.settings.invertColorsInDarkMode && document.body.classList.contains("theme-dark");
  }
  convertBlackSvgToWhite(svg) {
    return svg.replaceAll("rgb(0%,0%,0%)", "rgb(100%,100%,100%)").replace(new RegExp("rgb[(]0%,[ \\t]*0%,[ \\t]*0%[)]", "g"), "rgb(100%,100%,100%)").replace(new RegExp("rgb[(]0,[ \\t]*0,[ \\t]*0[)]", "g"), "rgb(255,255,255)").replace(new RegExp("#000000(?![0-9a-f])", "gi"), "#ffffff").replace(new RegExp("#000(?![0-9a-f])", "gi"), "#fff").replace(new RegExp("stroke:[ \\t]*black", "gi"), "stroke:white").replace(new RegExp("fill:[ \\t]*black", "gi"), "fill:white").replace(new RegExp('stroke="black"', "gi"), 'stroke="white"').replace(new RegExp('fill="black"', "gi"), 'fill="white"');
  }
  renderTikz(source, el) {
    return __async(this, null, function* () {
      var _a;
      const result = yield this.renderTikzToSvgDataUrl(source);
      if (!result.ok || !result.dataUrl || !result.svgText) {
        this.showError(el, (_a = result.error) != null ? _a : "Render error.", result.rawLog);
        return;
      }
      el.empty();
      const block = el.createDiv({ cls: "tikzjax-hebrew-local-block" });
      this.createDiagramToolbar(block, result.svgText);
      const container = block.createDiv({ cls: "tikzjax-hebrew-local-output" });
      const img = container.createEl("img");
      img.setAttr("src", result.dataUrl);
      img.setAttr("alt", "TikZ diagram");
      img.addClass("tikzjax-hebrew-local-image");
    });
  }
  showError(el, message, details) {
    el.empty();
    const errorEl = el.createDiv({ cls: "tikzjax-hebrew-local-error" });
    const titleEl = errorEl.createDiv({ cls: "tikzjax-hebrew-local-error-title" });
    titleEl.setText(message);
    if (!details) {
      return;
    }
    const buttonRow = errorEl.createDiv({
      cls: "tikzjax-hebrew-local-error-button-row"
    });
    const copyButton = buttonRow.createEl("button", {
      text: "Copy error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    copyButton.addEventListener("click", () => __async(this, null, function* () {
      try {
        yield navigator.clipboard.writeText(details);
        new import_obsidian2.Notice("LuaTikZ error copied.");
      } catch (e) {
        new import_obsidian2.Notice("Could not copy error.");
      }
    }));
    const button = buttonRow.createEl("button", {
      text: "Show full error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    const detailsEl = errorEl.createEl("pre", {
      cls: "tikzjax-hebrew-local-error-details"
    });
    detailsEl.setText(details);
    detailsEl.style.display = "none";
    button.addEventListener("click", () => {
      const isHidden = detailsEl.style.display === "none";
      detailsEl.style.display = isHidden ? "block" : "none";
      button.setText(isHidden ? "Hide full error" : "Show full error");
    });
  }
  addSyntaxHighlighting() {
    window.CodeMirror.modeInfo.push({ name: "Tikz", mime: "text/x-latex", mode: "stex" });
  }
  removeSyntaxHighlighting() {
    window.CodeMirror.modeInfo = window.CodeMirror.modeInfo.filter((el) => el.name != "Tikz");
  }
  tidyTikzSource(tikzSource) {
    const remove = "&nbsp;";
    tikzSource = tikzSource.replaceAll(remove, "");
    let lines = tikzSource.split("\n");
    lines = lines.map((line) => line.trim());
    lines = lines.filter((line) => line);
    return lines.join("\n");
  }
};
