/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
__export(exports, {
  default: () => TikzjaxHebrewLocalPlugin
});
var import_obsidian2 = __toModule(require("obsidian"));
var import_child_process = __toModule(require("child_process"));
var import_util = __toModule(require("util"));

// latexAutocomplete.ts
var import_autocomplete = __toModule(require("@codemirror/autocomplete"));
var latexCommands = [
  {
    label: "\\begin{tikzpicture}",
    type: "keyword",
    apply: `\\begin{tikzpicture}
  
\\end{tikzpicture}`,
    detail: "TikZ environment"
  },
  {
    label: "\\end{tikzpicture}",
    type: "keyword",
    apply: "\\end{tikzpicture}",
    detail: "End TikZ environment"
  },
  {
    label: "\\draw",
    type: "function",
    apply: "\\draw ",
    detail: "TikZ draw command"
  },
  {
    label: "\\node",
    type: "function",
    apply: "\\node ",
    detail: "TikZ node command"
  },
  {
    label: "\\coordinate",
    type: "function",
    apply: "\\coordinate ",
    detail: "TikZ coordinate"
  },
  {
    label: "\\he{}",
    type: "function",
    apply: "\\he{}",
    detail: "Hebrew text wrapper"
  },
  {
    label: "\\frac{}{}",
    type: "function",
    apply: "\\frac{}{}",
    detail: "Fraction"
  },
  {
    label: "\\cfrac{}{}",
    type: "function",
    apply: "\\cfrac{}{}",
    detail: "Display fraction"
  },
  {
    label: "\\sqrt{}",
    type: "function",
    apply: "\\sqrt{}",
    detail: "Square root"
  },
  {
    label: "\\sum_{}^{}",
    type: "function",
    apply: "\\sum_{}^{}",
    detail: "Summation"
  },
  {
    label: "\\int_{}^{}",
    type: "function",
    apply: "\\int_{}^{}",
    detail: "Integral"
  },
  {
    label: "\\alpha",
    type: "variable",
    apply: "\\alpha"
  },
  {
    label: "\\beta",
    type: "variable",
    apply: "\\beta"
  },
  {
    label: "\\gamma",
    type: "variable",
    apply: "\\gamma"
  },
  {
    label: "\\Delta",
    type: "variable",
    apply: "\\Delta"
  },
  {
    label: "\\theta",
    type: "variable",
    apply: "\\theta"
  }
];
var tikzOptions = [
  {
    label: "thick",
    type: "property",
    apply: "thick"
  },
  {
    label: "very thick",
    type: "property",
    apply: "very thick"
  },
  {
    label: "dashed",
    type: "property",
    apply: "dashed"
  },
  {
    label: "fill=cyan!10",
    type: "property",
    apply: "fill=cyan!10"
  },
  {
    label: "draw=black",
    type: "property",
    apply: "draw=black"
  },
  {
    label: "circle",
    type: "property",
    apply: "circle"
  },
  {
    label: "rectangle",
    type: "property",
    apply: "rectangle"
  },
  {
    label: "font=\\small",
    type: "property",
    apply: "font=\\small"
  },
  {
    label: "align=center",
    type: "property",
    apply: "align=center"
  },
  {
    label: "inner sep=2pt",
    type: "property",
    apply: "inner sep=2pt"
  }
];
function insideLatexOrTikzBlock(textBeforeCursor) {
  const lastFence = textBeforeCursor.lastIndexOf("```");
  if (lastFence === -1) {
    return false;
  }
  const afterFence = textBeforeCursor.slice(lastFence);
  return afterFence.startsWith("```tikz") || afterFence.startsWith("```latex") || afterFence.startsWith("```lualatex") || afterFence.startsWith("```tex");
}
function latexCompletionSource(context) {
  const textBeforeCursor = context.state.doc.sliceString(0, context.pos);
  if (!insideLatexOrTikzBlock(textBeforeCursor)) {
    return null;
  }
  const commandMatch = context.matchBefore(/\\[A-Za-z]*/);
  if (commandMatch) {
    return {
      from: commandMatch.from,
      options: latexCommands,
      validFor: /^\\[A-Za-z]*$/
    };
  }
  const optionMatch = context.matchBefore(/[A-Za-z!\\=0-9.-]+/);
  if (optionMatch && context.explicit) {
    return {
      from: optionMatch.from,
      options: tikzOptions,
      validFor: /^[A-Za-z!\\=0-9.-]*$/
    };
  }
  return null;
}
function latexAutocompleteExtension() {
  return (0, import_autocomplete.autocompletion)({
    override: [latexCompletionSource],
    activateOnTyping: true
  });
}

// simpleShapes.ts
var SIMPLE_TIKZ_HELPERS = String.raw`
% ---------- Simple drawing helpers ----------
\def\Circle(#1,#2,#3){\draw (#1,#2) circle (#3);}
\def\FilledCircle(#1,#2,#3){\fill (#1,#2) circle (#3);}
\def\Point(#1,#2){\fill (#1,#2) circle (1.7pt);}
\def\Line(#1,#2,#3,#4){\draw (#1,#2) -- (#3,#4);}
\def\Arrow(#1,#2,#3,#4){\draw[->] (#1,#2) -- (#3,#4);}
\def\Rect(#1,#2,#3,#4){\draw (#1,#2) rectangle (#3,#4);}
\def\FilledRect(#1,#2,#3,#4){\fill (#1,#2) rectangle (#3,#4);}
\def\Axis(#1,#2,#3,#4){
\draw[->] (#1,0) -- (#2,0) node[right] {$x$};
\draw[->] (0,#3) -- (0,#4) node[above] {$y$};
}
\def\AxisNamed(#1,#2,#3,#4,#5,#6){
\draw[->] (#1,0) -- (#2,0) node[right] {#5};
\draw[->] (0,#3) -- (0,#4) node[above] {#6};
}

% ---------- Simple text helpers ----------
\def\Text(#1,#2,#3){\node at (#1,#2) {#3};}
\def\SmallText(#1,#2,#3){\node[font=\small] at (#1,#2) {#3};}
\def\TinyText(#1,#2,#3){\node[font=\tiny] at (#1,#2) {#3};}

% ---------- Simple logic gates ----------
\def\ANDgate(#1,#2,#3){
\node[and gate US, draw, logic gate inputs=nn, anchor=input 1] (#3) at (#1,#2) {};
}

\def\ORgate(#1,#2,#3){
\node[or gate US, draw, logic gate inputs=nn, anchor=input 1] (#3) at (#1,#2) {};
}

\def\NOTgate(#1,#2,#3){
\node[not gate US, draw, anchor=input] (#3) at (#1,#2) {};
}

% ---------- Logic-gate wire helpers ----------
\def\LogicWire(#1,#2){
\draw (#1) -- ++(0.35,0) |- (#2);
}

\def\LogicWireArrow(#1,#2){
\draw[->] (#1) -- ++(0.35,0) |- (#2);
}

\def\LogicWireDirect(#1,#2){
\draw (#1) -- (#2);
}

\def\LogicWireFrom(#1,#2,#3){
\draw (#1,#2) -- ++(0.35,0) |- (#3);
}

\def\LogicWireFromArrow(#1,#2,#3){
\draw[->] (#1,#2) -- ++(0.35,0) |- (#3);
}

\def\LogicWireTo(#1,#2,#3){
\draw (#1) -- ++(0.35,0) |- (#2,#3);
}

\def\LogicWireToArrow(#1,#2,#3){
\draw[->] (#1) -- ++(0.35,0) |- (#2,#3);
}
\def\Triangle(#1,#2,#3,#4,#5,#6){
\draw (#1,#2) -- (#3,#4) -- (#5,#6) -- cycle;
}

\def\FilledTriangle(#1,#2,#3,#4,#5,#6){
\fill (#1,#2) -- (#3,#4) -- (#5,#6) -- cycle;
}
% ---------- More logic gates ----------
\def\BUFFERgate(#1,#2,#3){
\node[buffer gate US, draw, anchor=input] (#3) at (#1,#2) {};
}

\def\NANDgate(#1,#2,#3){
\node[nand gate US, draw, logic gate inputs=nn, anchor=input 1] (#3) at (#1,#2) {};
}

\def\NORgate(#1,#2,#3){
\node[nor gate US, draw, logic gate inputs=nn, anchor=input 1] (#3) at (#1,#2) {};
}

\def\XORgate(#1,#2,#3){
\node[xor gate US, draw, logic gate inputs=nn, anchor=input 1] (#3) at (#1,#2) {};
}

\def\XNORgate(#1,#2,#3){
\node[xnor gate US, draw, logic gate inputs=nn, anchor=input 1] (#3) at (#1,#2) {};
}
`;

// settings.ts
var import_obsidian = __toModule(require("obsidian"));
var TikzjaxSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Invert dark colors in dark mode").setDesc("Invert dark colors in diagrams (e.g. axes, arrows) when in dark mode, so that they are visible.").addToggle((toggle) => toggle.setValue(this.plugin.settings.invertColorsInDarkMode).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.invertColorsInDarkMode = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian.Setting(containerEl).setName("Enable inline live preview by default").setDesc("Automatically show the floating live TikZ preview when the cursor is inside a TikZ block.").addToggle((toggle) => toggle.setValue(this.plugin.settings.inlineLivePreviewEnabledByDefault).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.inlineLivePreviewEnabledByDefault = value;
      yield this.plugin.saveSettings();
    })));
  }
};

// main.ts
var fs = __toModule(require("fs"));
var path = __toModule(require("path"));
var os = __toModule(require("os"));
var DEFAULT_SETTINGS = {
  invertColorsInDarkMode: true,
  inlineLivePreviewEnabledByDefault: true
};
var execFileAsync = (0, import_util.promisify)(import_child_process.execFile);
var DOCUMENTCLASS_LINE = "\\documentclass[tikz,border=5pt]{standalone}\n";
var LATEX_WRAPPER_PREFIX = `${DOCUMENTCLASS_LINE}\\usepackage{fontspec}
\\usepackage{polyglossia}

\\setmainlanguage{english}
\\setotherlanguage{hebrew}

\\newfontfamily\\hebrewfont[Script=Hebrew]{David CLM}
\\newfontfamily\\hebrewfontsf[Script=Hebrew]{David CLM}
\\newfontfamily\\hebrewfonttt[Script=Hebrew]{David CLM}

\\usepackage{tikz}
\\usetikzlibrary{arrows.meta,positioning,calc,shapes,decorations.pathmorphing,shapes.gates.logic.US}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{circuitikz}
\\usepackage{pgfplots}
\\pgfplotsset{compat=1.18}

\\newcommand{\\he}[1]{\\texthebrew{#1}}
${SIMPLE_TIKZ_HELPERS}
\\begin{document}
`;
var LATEX_WRAPPER_SUFFIX = `
\\end{document}
`;
function fileExists(filePath) {
  return __async(this, null, function* () {
    return fs.existsSync(filePath);
  });
}
function resolveCommand(commandName, candidates) {
  return __async(this, null, function* () {
    for (const candidate of candidates) {
      if (candidate.includes("/")) {
        if (yield fileExists(candidate)) {
          return candidate;
        }
        continue;
      }
      try {
        const { stdout } = yield execFileAsync("/usr/bin/which", [candidate]);
        const resolved = stdout.trim();
        if (resolved) {
          return resolved;
        }
      } catch (e) {
      }
    }
    return null;
  });
}
function resolveLuaLatex() {
  return __async(this, null, function* () {
    return resolveCommand("lualatex", [
      "/Library/TeX/texbin/lualatex",
      "/usr/local/texlive/2025/bin/universal-darwin/lualatex",
      "/usr/local/bin/lualatex",
      "lualatex"
    ]);
  });
}
function resolvePdfToCairo() {
  return __async(this, null, function* () {
    return resolveCommand("pdftocairo", [
      "/opt/homebrew/bin/pdftocairo",
      "/usr/local/bin/pdftocairo",
      "/usr/bin/pdftocairo",
      "pdftocairo"
    ]);
  });
}
function wrapLatexSource(source) {
  let cleanedSource = source;
  cleanedSource = cleanedSource.replace(/\\documentclass(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\usepackage(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\pgfplotsset\{[^}]*\}/g, "");
  cleanedSource = cleanedSource.replace(/\\begin\{document\}/g, "");
  cleanedSource = cleanedSource.replace(/\\end\{document\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setmainlanguage\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setotherlanguage\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setmainfont(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\setsansfont(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  cleanedSource = cleanedSource.replace(/\\newfontfamily\\\w+(?:\[[^\]]*\])?\{[^}]+\}/g, "");
  return LATEX_WRAPPER_PREFIX + cleanedSource.trim() + LATEX_WRAPPER_SUFFIX;
}
function readLogTail(logPath, maxChars = 8e3) {
  if (!fs.existsSync(logPath)) {
    return "";
  }
  const log = fs.readFileSync(logPath, "utf8");
  if (log.length <= maxChars) {
    return log;
  }
  return "...(truncated)...\n" + log.slice(-maxChars);
}
function formatExecError(err) {
  if (err instanceof Error) {
    const execErr = err;
    const parts = [execErr.message];
    if (execErr.stdout) {
      parts.push(execErr.stdout);
    }
    if (execErr.stderr) {
      parts.push(execErr.stderr);
    }
    return parts.join("\n");
  }
  return String(err);
}
function extractUsefulLatexError(raw) {
  const lines = raw.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  const bangLine = lines.find((line) => line.startsWith("! "));
  if (bangLine) {
    return bangLine.replace(/^!\s*/, "").trim();
  }
  const usefulLine = lines.find((line) => line.includes("Undefined control sequence") || line.includes("Missing") || line.includes("Runaway argument") || line.includes("Fatal error"));
  if (usefulLine) {
    return usefulLine.trim();
  }
  return "Syntax error";
}
function getCurrentTikzBlock(editor) {
  const cursor = editor.getCursor();
  const lineCount = editor.lineCount();
  let startLine = -1;
  for (let line = cursor.line; line >= 0; line--) {
    const text = editor.getLine(line).trim();
    if (text.startsWith("```tikz")) {
      startLine = line;
      break;
    }
    if (text === "```") {
      return null;
    }
  }
  if (startLine === -1) {
    return null;
  }
  let endLine = -1;
  for (let line = startLine + 1; line < lineCount; line++) {
    const text = editor.getLine(line).trim();
    if (text === "```") {
      endLine = line;
      break;
    }
  }
  if (endLine === -1) {
    return null;
  }
  if (cursor.line <= startLine || cursor.line >= endLine) {
    return null;
  }
  const source = editor.getRange({ line: startLine + 1, ch: 0 }, { line: endLine, ch: 0 });
  return {
    source,
    startLine,
    endLine
  };
}
var TikzjaxHebrewLocalPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.inlinePreviewEnabled = false;
    this.inlinePreviewContainer = null;
    this.inlinePreviewTimer = null;
    this.inlinePreviewLastGoodDataUrl = null;
    this.inlinePreviewLastSource = null;
    this.inlinePreviewRenderToken = 0;
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.registerEditorExtension(latexAutocompleteExtension());
      this.addCommand({
        id: "toggle-tikz-inline-live-preview",
        name: "LuaTikZ: Toggle inline live preview",
        callback: () => {
          this.toggleInlineLivePreview();
        }
      });
      this.registerEvent(this.app.workspace.on("editor-change", () => {
        this.scheduleInlinePreviewUpdate();
      }));
      this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
        this.scheduleInlinePreviewUpdate();
      }));
      this.registerDomEvent(document, "selectionchange", () => {
        this.scheduleInlinePreviewUpdate();
      });
      this.addSettingTab(new TikzjaxSettingTab(this.app, this));
      this.addSyntaxHighlighting();
      this.registerTikzCodeBlock();
      if (this.settings.inlineLivePreviewEnabledByDefault) {
        this.inlinePreviewEnabled = true;
        this.scheduleInlinePreviewUpdate(500);
      }
    });
  }
  onunload() {
    this.removeSyntaxHighlighting();
    this.disableInlineLivePreview();
    if (this.inlinePreviewTimer) {
      window.clearTimeout(this.inlinePreviewTimer);
    }
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  registerTikzCodeBlock() {
    this.registerMarkdownCodeBlockProcessor("tikz", (source, el) => __async(this, null, function* () {
      el.empty();
      const loadingEl = el.createDiv({ cls: "tikzjax-hebrew-local-output" });
      loadingEl.setText("Rendering TikZ diagram\u2026");
      try {
        const cleanedSource = this.tidyTikzSource(source);
        if (!cleanedSource.trim()) {
          this.showError(el, "Nothing to render.");
          return;
        }
        yield this.renderTikz(cleanedSource, el);
      } catch (err) {
        this.showError(el, "Render error.", formatExecError(err));
      }
    }));
  }
  toggleInlineLivePreview() {
    if (this.inlinePreviewEnabled) {
      this.disableInlineLivePreview();
      new import_obsidian2.Notice("LuaTikZ inline live preview disabled.");
      return;
    }
    this.inlinePreviewEnabled = true;
    new import_obsidian2.Notice("LuaTikZ inline live preview enabled.");
    this.scheduleInlinePreviewUpdate(0);
  }
  disableInlineLivePreview() {
    this.inlinePreviewEnabled = false;
    this.inlinePreviewLastGoodDataUrl = null;
    this.inlinePreviewLastSource = null;
    if (this.inlinePreviewTimer) {
      window.clearTimeout(this.inlinePreviewTimer);
      this.inlinePreviewTimer = null;
    }
    if (this.inlinePreviewContainer) {
      this.inlinePreviewContainer.remove();
      this.inlinePreviewContainer = null;
    }
  }
  scheduleInlinePreviewUpdate(delay = 800) {
    if (!this.inlinePreviewEnabled) {
      return;
    }
    if (this.inlinePreviewTimer) {
      window.clearTimeout(this.inlinePreviewTimer);
    }
    this.inlinePreviewTimer = window.setTimeout(() => {
      this.updateInlinePreviewFromActiveEditor();
    }, delay);
  }
  getActiveMarkdownView() {
    return this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
  }
  getOrCreateInlinePreviewContainer(markdownView) {
    if (this.inlinePreviewContainer && document.body.contains(this.inlinePreviewContainer)) {
      return this.inlinePreviewContainer;
    }
    const container = markdownView.containerEl.createDiv({
      cls: "tikzjax-hebrew-local-inline-preview"
    });
    this.inlinePreviewContainer = container;
    return container;
  }
  hideInlinePreview() {
    if (this.inlinePreviewContainer) {
      this.inlinePreviewContainer.remove();
      this.inlinePreviewContainer = null;
    }
  }
  showInlineMessage(markdownView, message) {
    const container = this.getOrCreateInlinePreviewContainer(markdownView);
    container.empty();
    container.createDiv({
      cls: "tikzjax-hebrew-local-inline-preview-message",
      text: message
    });
  }
  showInlineImage(markdownView, dataUrl) {
    const container = this.getOrCreateInlinePreviewContainer(markdownView);
    container.empty();
    const output = container.createDiv({
      cls: "tikzjax-hebrew-local-output"
    });
    const img = output.createEl("img");
    img.setAttr("src", dataUrl);
    img.setAttr("alt", "TikZ diagram");
    img.addClass("tikzjax-hebrew-local-image");
  }
  showInlineError(markdownView, message, details) {
    const container = this.getOrCreateInlinePreviewContainer(markdownView);
    const errorEl = container.createDiv({
      cls: "tikzjax-hebrew-local-error tikzjax-hebrew-local-inline-preview-error"
    });
    const titleEl = errorEl.createDiv({
      cls: "tikzjax-hebrew-local-error-title"
    });
    titleEl.setText(message);
    if (!details) {
      return;
    }
    const buttonRow = errorEl.createDiv({
      cls: "tikzjax-hebrew-local-error-button-row"
    });
    const copyButton = buttonRow.createEl("button", {
      text: "Copy error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    copyButton.addEventListener("click", () => __async(this, null, function* () {
      try {
        yield navigator.clipboard.writeText(details);
        new import_obsidian2.Notice("LuaTikZ error copied.");
      } catch (e) {
        new import_obsidian2.Notice("Could not copy error.");
      }
    }));
    const button = buttonRow.createEl("button", {
      text: "Show full error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    const detailsEl = errorEl.createEl("pre", {
      cls: "tikzjax-hebrew-local-error-details"
    });
    detailsEl.setText(details);
    detailsEl.style.display = "none";
    button.addEventListener("click", () => {
      const isHidden = detailsEl.style.display === "none";
      detailsEl.style.display = isHidden ? "block" : "none";
      button.setText(isHidden ? "Hide full error" : "Show full error");
    });
  }
  updateInlinePreviewFromActiveEditor() {
    return __async(this, null, function* () {
      var _a, _b;
      if (!this.inlinePreviewEnabled) {
        return;
      }
      const markdownView = this.getActiveMarkdownView();
      if (!markdownView) {
        this.hideInlinePreview();
        return;
      }
      const block = getCurrentTikzBlock(markdownView.editor);
      if (!block) {
        this.hideInlinePreview();
        return;
      }
      const cleanedSource = this.tidyTikzSource(block.source);
      if (!cleanedSource.trim()) {
        this.showInlineMessage(markdownView, "Nothing to render.");
        return;
      }
      if (cleanedSource === this.inlinePreviewLastSource && this.inlinePreviewLastGoodDataUrl) {
        return;
      }
      const token = ++this.inlinePreviewRenderToken;
      if (!this.inlinePreviewLastGoodDataUrl) {
        this.showInlineMessage(markdownView, "Rendering TikZ diagram\u2026");
      }
      const result = yield this.renderTikzToSvgDataUrl(cleanedSource);
      if (token !== this.inlinePreviewRenderToken) {
        return;
      }
      if (result.ok && result.dataUrl) {
        this.inlinePreviewLastSource = cleanedSource;
        this.inlinePreviewLastGoodDataUrl = result.dataUrl;
        this.showInlineImage(markdownView, result.dataUrl);
        return;
      }
      if (this.inlinePreviewLastGoodDataUrl) {
        this.showInlineImage(markdownView, this.inlinePreviewLastGoodDataUrl);
        this.showInlineError(markdownView, (_a = result.error) != null ? _a : "Render error.", result.rawLog);
        return;
      }
      const container = this.getOrCreateInlinePreviewContainer(markdownView);
      container.empty();
      this.showInlineError(markdownView, (_b = result.error) != null ? _b : "Render error.", result.rawLog);
    });
  }
  renderTikzToSvgDataUrl(source) {
    return __async(this, null, function* () {
      const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "obsidian-tikz-hebrew-"));
      const texPath = path.join(tmpDir, "diagram.tex");
      const pdfPath = path.join(tmpDir, "diagram.pdf");
      const logPath = path.join(tmpDir, "diagram.log");
      const svgPath = path.join(tmpDir, "diagram.svg");
      const wrappedSource = wrapLatexSource(source);
      fs.writeFileSync(texPath, wrappedSource, "utf8");
      const lualatexPath = yield resolveLuaLatex();
      if (!lualatexPath) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "LuaLaTeX was not found.",
          rawLog: "On macOS, LuaLaTeX is usually located at:\n/Library/TeX/texbin/lualatex\n\nCheck in Terminal with:\nwhich lualatex"
        };
      }
      try {
        yield execFileAsync(lualatexPath, [
          "-interaction=nonstopmode",
          "-halt-on-error",
          `-output-directory=${tmpDir}`,
          texPath
        ], {
          cwd: tmpDir,
          maxBuffer: 10 * 1024 * 1024
        });
      } catch (err) {
        const logTail = readLogTail(logPath);
        const rawError = [
          formatExecError(err),
          logTail ? "\n--- diagram.log (tail) ---\n" + logTail : ""
        ].join("\n");
        const usefulError = extractUsefulLatexError(rawError);
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: `Syntax error: ${usefulError}`,
          rawLog: rawError
        };
      }
      if (!fs.existsSync(pdfPath)) {
        const logTail = readLogTail(logPath);
        const details = [
          "LuaLaTeX finished but diagram.pdf was not produced."
        ];
        if (logTail) {
          details.push("", "--- diagram.log (tail) ---", logTail);
        }
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "LuaLaTeX finished, but no PDF was produced.",
          rawLog: details.join("\n")
        };
      }
      const pdftocairoPath = yield resolvePdfToCairo();
      if (!pdftocairoPath) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "PDF rendered, but SVG conversion is not available.",
          rawLog: `pdftocairo was not found.

Install it with:
brew install poppler

PDF path: ${pdfPath}`
        };
      }
      try {
        yield execFileAsync(pdftocairoPath, [
          "-svg",
          pdfPath,
          svgPath
        ], {
          cwd: tmpDir,
          maxBuffer: 30 * 1024 * 1024
        });
      } catch (err) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "PDF rendered, but SVG conversion failed.",
          rawLog: `PDF path: ${pdfPath}

${formatExecError(err)}`
        };
      }
      if (!fs.existsSync(svgPath)) {
        this.cleanupTempDir(tmpDir);
        return {
          ok: false,
          error: "PDF rendered, but no SVG was produced.",
          rawLog: `PDF path: ${pdfPath}`
        };
      }
      let svgText = fs.readFileSync(svgPath, "utf8");
      if (this.shouldConvertBlackToWhite()) {
        svgText = this.convertBlackSvgToWhite(svgText);
      }
      const svgBase64 = Buffer.from(svgText, "utf8").toString("base64");
      this.cleanupTempDir(tmpDir);
      return {
        ok: true,
        dataUrl: `data:image/svg+xml;base64,${svgBase64}`
      };
    });
  }
  cleanupTempDir(tmpDir) {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch (e) {
    }
  }
  shouldConvertBlackToWhite() {
    return this.settings.invertColorsInDarkMode && document.body.classList.contains("theme-dark");
  }
  convertBlackSvgToWhite(svg) {
    return svg.replaceAll("rgb(0%,0%,0%)", "rgb(100%,100%,100%)").replace(new RegExp("rgb[(]0%,[ \\t]*0%,[ \\t]*0%[)]", "g"), "rgb(100%,100%,100%)").replace(new RegExp("rgb[(]0,[ \\t]*0,[ \\t]*0[)]", "g"), "rgb(255,255,255)").replace(new RegExp("#000000(?![0-9a-f])", "gi"), "#ffffff").replace(new RegExp("#000(?![0-9a-f])", "gi"), "#fff").replace(new RegExp("stroke:[ \\t]*black", "gi"), "stroke:white").replace(new RegExp("fill:[ \\t]*black", "gi"), "fill:white").replace(new RegExp('stroke="black"', "gi"), 'stroke="white"').replace(new RegExp('fill="black"', "gi"), 'fill="white"');
  }
  renderTikz(source, el) {
    return __async(this, null, function* () {
      var _a;
      const result = yield this.renderTikzToSvgDataUrl(source);
      if (!result.ok || !result.dataUrl) {
        this.showError(el, (_a = result.error) != null ? _a : "Render error.", result.rawLog);
        return;
      }
      el.empty();
      const container = el.createDiv({ cls: "tikzjax-hebrew-local-output" });
      const img = container.createEl("img");
      img.setAttr("src", result.dataUrl);
      img.setAttr("alt", "TikZ diagram");
      img.addClass("tikzjax-hebrew-local-image");
    });
  }
  showError(el, message, details) {
    el.empty();
    const errorEl = el.createDiv({ cls: "tikzjax-hebrew-local-error" });
    const titleEl = errorEl.createDiv({ cls: "tikzjax-hebrew-local-error-title" });
    titleEl.setText(message);
    if (!details) {
      return;
    }
    const buttonRow = errorEl.createDiv({
      cls: "tikzjax-hebrew-local-error-button-row"
    });
    const copyButton = buttonRow.createEl("button", {
      text: "Copy error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    copyButton.addEventListener("click", () => __async(this, null, function* () {
      try {
        yield navigator.clipboard.writeText(details);
        new import_obsidian2.Notice("LuaTikZ error copied.");
      } catch (e) {
        new import_obsidian2.Notice("Could not copy error.");
      }
    }));
    const button = buttonRow.createEl("button", {
      text: "Show full error",
      cls: "tikzjax-hebrew-local-error-button"
    });
    const detailsEl = errorEl.createEl("pre", {
      cls: "tikzjax-hebrew-local-error-details"
    });
    detailsEl.setText(details);
    detailsEl.style.display = "none";
    button.addEventListener("click", () => {
      const isHidden = detailsEl.style.display === "none";
      detailsEl.style.display = isHidden ? "block" : "none";
      button.setText(isHidden ? "Hide full error" : "Show full error");
    });
  }
  addSyntaxHighlighting() {
    window.CodeMirror.modeInfo.push({ name: "Tikz", mime: "text/x-latex", mode: "stex" });
  }
  removeSyntaxHighlighting() {
    window.CodeMirror.modeInfo = window.CodeMirror.modeInfo.filter((el) => el.name != "Tikz");
  }
  tidyTikzSource(tikzSource) {
    const remove = "&nbsp;";
    tikzSource = tikzSource.replaceAll(remove, "");
    let lines = tikzSource.split("\n");
    lines = lines.map((line) => line.trim());
    lines = lines.filter((line) => line);
    return lines.join("\n");
  }
};
